/* tslint:disable */
/* eslint-disable */
/**
 * DCS (Gitea) API.
 * This documentation describes the DCS (Gitea) API.
 *
 * OpenAPI spec version: 1.16.7+dcs
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */export * from './apis/admin-api';
export * from './apis/issue-api';
export * from './apis/miscellaneous-api';
export * from './apis/notification-api';
export * from './apis/organization-api';
export * from './apis/repository-api';
export * from './apis/settings-api';
export * from './apis/user-api';

