/* tslint:disable */
/* eslint-disable */
/**
 * DCS (Gitea) API.
 * This documentation describes the DCS (Gitea) API.
 *
 * OpenAPI spec version: 1.16.7+dcs
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface AccessToken
 */
export interface AccessToken {
    /**
     * 
     * @type {number}
     * @memberof AccessToken
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof AccessToken
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof AccessToken
     */
    sha1?: string;
    /**
     * 
     * @type {string}
     * @memberof AccessToken
     */
    tokenLastEight?: string;
}
