/* tslint:disable */
/* eslint-disable */
/**
 * DCS (Gitea) API.
 * This documentation describes the DCS (Gitea) API.
 *
 * OpenAPI spec version: 1.16.7+dcs
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * AddTimeOption options for adding time to an issue
 * @export
 * @interface AddTimeOption
 */
export interface AddTimeOption {
    /**
     * 
     * @type {Date}
     * @memberof AddTimeOption
     */
    created?: Date;
    /**
     * time in seconds
     * @type {number}
     * @memberof AddTimeOption
     */
    time: number;
    /**
     * User who spent the time (optional)
     * @type {string}
     * @memberof AddTimeOption
     */
    userName?: string;
}
