/* tslint:disable */
/* eslint-disable */
/**
 * DCS (Gitea) API.
 * This documentation describes the DCS (Gitea) API.
 *
 * OpenAPI spec version: 1.16.7+dcs
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { PayloadCommit } from './payload-commit';
/**
 * Branch represents a repository branch
 * @export
 * @interface Branch
 */
export interface Branch {
    /**
     * 
     * @type {PayloadCommit}
     * @memberof Branch
     */
    commit?: PayloadCommit;
    /**
     * 
     * @type {string}
     * @memberof Branch
     */
    effectiveBranchProtectionName?: string;
    /**
     * 
     * @type {boolean}
     * @memberof Branch
     */
    enableStatusCheck?: boolean;
    /**
     * 
     * @type {string}
     * @memberof Branch
     */
    name?: string;
    /**
     * 
     * @type {boolean}
     * @memberof Branch
     */
    _protected?: boolean;
    /**
     * 
     * @type {number}
     * @memberof Branch
     */
    requiredApprovals?: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof Branch
     */
    statusCheckContexts?: Array<string>;
    /**
     * 
     * @type {boolean}
     * @memberof Branch
     */
    userCanMerge?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Branch
     */
    userCanPush?: boolean;
}
