/* tslint:disable */
/* eslint-disable */
/**
 * DCS (Gitea) API.
 * This documentation describes the DCS (Gitea) API.
 *
 * OpenAPI spec version: 1.16.7+dcs
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CatalogStage } from './catalog-stage';
/**
 * CatalogStages a repo's catalog stages
 * @export
 * @interface CatalogStages
 */
export interface CatalogStages {
    /**
     * 
     * @type {CatalogStage}
     * @memberof CatalogStages
     */
    draft?: CatalogStage;
    /**
     * 
     * @type {CatalogStage}
     * @memberof CatalogStages
     */
    latest?: CatalogStage;
    /**
     * 
     * @type {CatalogStage}
     * @memberof CatalogStages
     */
    preprod?: CatalogStage;
    /**
     * 
     * @type {CatalogStage}
     * @memberof CatalogStages
     */
    prod?: CatalogStage;
}
