/* tslint:disable */
/* eslint-disable */
/**
 * DCS (Gitea) API.
 * This documentation describes the DCS (Gitea) API.
 *
 * OpenAPI spec version: 1.16.7+dcs
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CommitStatus } from './commit-status';
import { CommitStatusState } from './commit-status-state';
import { Repository } from './repository';
/**
 * CombinedStatus holds the combined state of several statuses for a single commit
 * @export
 * @interface CombinedStatus
 */
export interface CombinedStatus {
    /**
     * 
     * @type {string}
     * @memberof CombinedStatus
     */
    commitUrl?: string;
    /**
     * 
     * @type {Repository}
     * @memberof CombinedStatus
     */
    repository?: Repository;
    /**
     * 
     * @type {string}
     * @memberof CombinedStatus
     */
    sha?: string;
    /**
     * 
     * @type {CommitStatusState}
     * @memberof CombinedStatus
     */
    state?: CommitStatusState;
    /**
     * 
     * @type {Array<CommitStatus>}
     * @memberof CombinedStatus
     */
    statuses?: Array<CommitStatus>;
    /**
     * 
     * @type {number}
     * @memberof CombinedStatus
     */
    totalCount?: number;
    /**
     * 
     * @type {string}
     * @memberof CombinedStatus
     */
    url?: string;
}
