/* tslint:disable */
/* eslint-disable */
/**
 * DCS (Gitea) API.
 * This documentation describes the DCS (Gitea) API.
 *
 * OpenAPI spec version: 1.16.7+dcs
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { FileLinksResponse } from './file-links-response';
/**
 * ContentsResponse contains information about a repo's entry's (dir, file, symlink, submodule) metadata and content
 * @export
 * @interface ContentsResponse
 */
export interface ContentsResponse {
    /**
     * 
     * @type {FileLinksResponse}
     * @memberof ContentsResponse
     */
    links?: FileLinksResponse;
    /**
     * `content` is populated when `type` is `file`, otherwise null
     * @type {string}
     * @memberof ContentsResponse
     */
    content?: string;
    /**
     * 
     * @type {string}
     * @memberof ContentsResponse
     */
    downloadUrl?: string;
    /**
     * `encoding` is populated when `type` is `file`, otherwise null
     * @type {string}
     * @memberof ContentsResponse
     */
    encoding?: string;
    /**
     * 
     * @type {string}
     * @memberof ContentsResponse
     */
    gitUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof ContentsResponse
     */
    htmlUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof ContentsResponse
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof ContentsResponse
     */
    path?: string;
    /**
     * 
     * @type {string}
     * @memberof ContentsResponse
     */
    sha?: string;
    /**
     * 
     * @type {number}
     * @memberof ContentsResponse
     */
    size?: number;
    /**
     * `submodule_git_url` is populated when `type` is `submodule`, otherwise null
     * @type {string}
     * @memberof ContentsResponse
     */
    submoduleGitUrl?: string;
    /**
     * `target` is populated when `type` is `symlink`, otherwise null
     * @type {string}
     * @memberof ContentsResponse
     */
    target?: string;
    /**
     * `type` will be `file`, `dir`, `symlink`, or `submodule`
     * @type {string}
     * @memberof ContentsResponse
     */
    type?: string;
    /**
     * 
     * @type {string}
     * @memberof ContentsResponse
     */
    url?: string;
}
