/* tslint:disable */
/* eslint-disable */
/**
 * DCS (Gitea) API.
 * This documentation describes the DCS (Gitea) API.
 *
 * OpenAPI spec version: 1.16.7+dcs
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * CreateMilestoneOption options for creating a milestone
 * @export
 * @interface CreateMilestoneOption
 */
export interface CreateMilestoneOption {
    /**
     * 
     * @type {string}
     * @memberof CreateMilestoneOption
     */
    description?: string;
    /**
     * 
     * @type {Date}
     * @memberof CreateMilestoneOption
     */
    dueOn?: Date;
    /**
     * 
     * @type {string}
     * @memberof CreateMilestoneOption
     */
    state?: CreateMilestoneOptionStateEnum;
    /**
     * 
     * @type {string}
     * @memberof CreateMilestoneOption
     */
    title?: string;
}

/**
    * @export
    * @enum {string}
    */
export enum CreateMilestoneOptionStateEnum {
    Open = 'open',
    Closed = 'closed'
}

