/* tslint:disable */
/* eslint-disable */
/**
 * DCS (Gitea) API.
 * This documentation describes the DCS (Gitea) API.
 *
 * OpenAPI spec version: 1.16.7+dcs
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * CreateReleaseOption options when creating a release
 * @export
 * @interface CreateReleaseOption
 */
export interface CreateReleaseOption {
    /**
     * 
     * @type {string}
     * @memberof CreateReleaseOption
     */
    body?: string;
    /**
     * 
     * @type {boolean}
     * @memberof CreateReleaseOption
     */
    draft?: boolean;
    /**
     * 
     * @type {string}
     * @memberof CreateReleaseOption
     */
    name?: string;
    /**
     * 
     * @type {boolean}
     * @memberof CreateReleaseOption
     */
    prerelease?: boolean;
    /**
     * 
     * @type {string}
     * @memberof CreateReleaseOption
     */
    tagName: string;
    /**
     * 
     * @type {string}
     * @memberof CreateReleaseOption
     */
    targetCommitish?: string;
}
