/* tslint:disable */
/* eslint-disable */
/**
 * DCS (Gitea) API.
 * This documentation describes the DCS (Gitea) API.
 *
 * OpenAPI spec version: 1.16.7+dcs
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * CreateGPGKeyOption options create user GPG key
 * @export
 * @interface CreateGPGKeyOption
 */
export interface CreateGPGKeyOption {
    /**
     * An armored GPG key to add
     * @type {string}
     * @memberof CreateGPGKeyOption
     */
    armoredPublicKey: string;
    /**
     * 
     * @type {string}
     * @memberof CreateGPGKeyOption
     */
    armoredSignature?: string;
}
