/* tslint:disable */
/* eslint-disable */
/**
 * DCS (Gitea) API.
 * This documentation describes the DCS (Gitea) API.
 *
 * OpenAPI spec version: 1.16.7+dcs
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * CreateIssueCommentOption options for creating a comment on an issue
 * @export
 * @interface CreateIssueCommentOption
 */
export interface CreateIssueCommentOption {
    /**
     * 
     * @type {string}
     * @memberof CreateIssueCommentOption
     */
    body: string;
}
