/* tslint:disable */
/* eslint-disable */
/**
 * DCS (Gitea) API.
 * This documentation describes the DCS (Gitea) API.
 *
 * OpenAPI spec version: 1.16.7+dcs
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * CreateHookOptionConfig has all config options in it required are \"content_type\" and \"url\" Required
 * @export
 * @interface CreateHookOptionConfig
 */
export interface CreateHookOptionConfig {
  "content_type": string,
  url: string,
  [additionalProperties: string]: any;
}
