/* tslint:disable */
/* eslint-disable */
/**
 * DCS (Gitea) API.
 * This documentation describes the DCS (Gitea) API.
 *
 * OpenAPI spec version: 1.16.7+dcs
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * CreateForkOption options for creating a fork
 * @export
 * @interface CreateForkOption
 */
export interface CreateForkOption {
    /**
     * name of the forked repository
     * @type {string}
     * @memberof CreateForkOption
     */
    name?: string;
    /**
     * organization name, if forking into an organization
     * @type {string}
     * @memberof CreateForkOption
     */
    organization?: string;
}
