/* tslint:disable */
/* eslint-disable */
/**
 * DCS (Gitea) API.
 * This documentation describes the DCS (Gitea) API.
 *
 * OpenAPI spec version: 1.16.7+dcs
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CreatePullReviewComment } from './create-pull-review-comment';
import { ReviewStateType } from './review-state-type';
/**
 * CreatePullReviewOptions are options to create a pull review
 * @export
 * @interface CreatePullReviewOptions
 */
export interface CreatePullReviewOptions {
    /**
     * 
     * @type {string}
     * @memberof CreatePullReviewOptions
     */
    body?: string;
    /**
     * 
     * @type {Array<CreatePullReviewComment>}
     * @memberof CreatePullReviewOptions
     */
    comments?: Array<CreatePullReviewComment>;
    /**
     * 
     * @type {string}
     * @memberof CreatePullReviewOptions
     */
    commitId?: string;
    /**
     * 
     * @type {ReviewStateType}
     * @memberof CreatePullReviewOptions
     */
    event?: ReviewStateType;
}
