/* tslint:disable */
/* eslint-disable */
/**
 * DCS (Gitea) API.
 * This documentation describes the DCS (Gitea) API.
 *
 * OpenAPI spec version: 1.16.7+dcs
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Repository } from './repository';
/**
 * DeployKey a deploy key
 * @export
 * @interface DeployKey
 */
export interface DeployKey {
    /**
     * 
     * @type {Date}
     * @memberof DeployKey
     */
    createdAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof DeployKey
     */
    fingerprint?: string;
    /**
     * 
     * @type {number}
     * @memberof DeployKey
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof DeployKey
     */
    key?: string;
    /**
     * 
     * @type {number}
     * @memberof DeployKey
     */
    keyId?: number;
    /**
     * 
     * @type {boolean}
     * @memberof DeployKey
     */
    readOnly?: boolean;
    /**
     * 
     * @type {Repository}
     * @memberof DeployKey
     */
    repository?: Repository;
    /**
     * 
     * @type {string}
     * @memberof DeployKey
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof DeployKey
     */
    url?: string;
}
