/* tslint:disable */
/* eslint-disable */
/**
 * DCS (Gitea) API.
 * This documentation describes the DCS (Gitea) API.
 *
 * OpenAPI spec version: 1.16.7+dcs
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * EditHookOption options when modify one hook
 * @export
 * @interface EditHookOption
 */
export interface EditHookOption {
    /**
     * 
     * @type {boolean}
     * @memberof EditHookOption
     */
    active?: boolean;
    /**
     * 
     * @type {string}
     * @memberof EditHookOption
     */
    branchFilter?: string;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof EditHookOption
     */
    config?: { [key: string]: string; };
    /**
     * 
     * @type {Array<string>}
     * @memberof EditHookOption
     */
    events?: Array<string>;
}
