/* tslint:disable */
/* eslint-disable */
/**
 * DCS (Gitea) API.
 * This documentation describes the DCS (Gitea) API.
 *
 * OpenAPI spec version: 1.16.7+dcs
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * EditUserOption edit user options
 * @export
 * @interface EditUserOption
 */
export interface EditUserOption {
    /**
     * 
     * @type {boolean}
     * @memberof EditUserOption
     */
    active?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof EditUserOption
     */
    admin?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof EditUserOption
     */
    allowCreateOrganization?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof EditUserOption
     */
    allowGitHook?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof EditUserOption
     */
    allowImportLocal?: boolean;
    /**
     * 
     * @type {string}
     * @memberof EditUserOption
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof EditUserOption
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof EditUserOption
     */
    fullName?: string;
    /**
     * 
     * @type {string}
     * @memberof EditUserOption
     */
    location?: string;
    /**
     * 
     * @type {string}
     * @memberof EditUserOption
     */
    loginName: string;
    /**
     * 
     * @type {number}
     * @memberof EditUserOption
     */
    maxRepoCreation?: number;
    /**
     * 
     * @type {boolean}
     * @memberof EditUserOption
     */
    mustChangePassword?: boolean;
    /**
     * 
     * @type {string}
     * @memberof EditUserOption
     */
    password?: string;
    /**
     * 
     * @type {boolean}
     * @memberof EditUserOption
     */
    prohibitLogin?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof EditUserOption
     */
    restricted?: boolean;
    /**
     * 
     * @type {number}
     * @memberof EditUserOption
     */
    sourceId: number;
    /**
     * 
     * @type {string}
     * @memberof EditUserOption
     */
    visibility?: string;
    /**
     * 
     * @type {string}
     * @memberof EditUserOption
     */
    website?: string;
}
