/* tslint:disable */
/* eslint-disable */
/**
 * DCS (Gitea) API.
 * This documentation describes the DCS (Gitea) API.
 *
 * OpenAPI spec version: 1.16.7+dcs
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * EditIssueOption options for editing an issue
 * @export
 * @interface EditIssueOption
 */
export interface EditIssueOption {
    /**
     * deprecated
     * @type {string}
     * @memberof EditIssueOption
     */
    assignee?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof EditIssueOption
     */
    assignees?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof EditIssueOption
     */
    body?: string;
    /**
     * 
     * @type {Date}
     * @memberof EditIssueOption
     */
    dueDate?: Date;
    /**
     * 
     * @type {number}
     * @memberof EditIssueOption
     */
    milestone?: number;
    /**
     * 
     * @type {string}
     * @memberof EditIssueOption
     */
    ref?: string;
    /**
     * 
     * @type {string}
     * @memberof EditIssueOption
     */
    state?: string;
    /**
     * 
     * @type {string}
     * @memberof EditIssueOption
     */
    title?: string;
    /**
     * 
     * @type {boolean}
     * @memberof EditIssueOption
     */
    unsetDueDate?: boolean;
}
