/* tslint:disable */
/* eslint-disable */
/**
 * DCS (Gitea) API.
 * This documentation describes the DCS (Gitea) API.
 *
 * OpenAPI spec version: 1.16.7+dcs
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * EditBranchProtectionOption options for editing a branch protection
 * @export
 * @interface EditBranchProtectionOption
 */
export interface EditBranchProtectionOption {
    /**
     * 
     * @type {Array<string>}
     * @memberof EditBranchProtectionOption
     */
    approvalsWhitelistTeams?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof EditBranchProtectionOption
     */
    approvalsWhitelistUsername?: Array<string>;
    /**
     * 
     * @type {boolean}
     * @memberof EditBranchProtectionOption
     */
    blockOnOfficialReviewRequests?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof EditBranchProtectionOption
     */
    blockOnOutdatedBranch?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof EditBranchProtectionOption
     */
    blockOnRejectedReviews?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof EditBranchProtectionOption
     */
    dismissStaleApprovals?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof EditBranchProtectionOption
     */
    enableApprovalsWhitelist?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof EditBranchProtectionOption
     */
    enableMergeWhitelist?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof EditBranchProtectionOption
     */
    enablePush?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof EditBranchProtectionOption
     */
    enablePushWhitelist?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof EditBranchProtectionOption
     */
    enableStatusCheck?: boolean;
    /**
     * 
     * @type {Array<string>}
     * @memberof EditBranchProtectionOption
     */
    mergeWhitelistTeams?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof EditBranchProtectionOption
     */
    mergeWhitelistUsernames?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof EditBranchProtectionOption
     */
    protectedFilePatterns?: string;
    /**
     * 
     * @type {boolean}
     * @memberof EditBranchProtectionOption
     */
    pushWhitelistDeployKeys?: boolean;
    /**
     * 
     * @type {Array<string>}
     * @memberof EditBranchProtectionOption
     */
    pushWhitelistTeams?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof EditBranchProtectionOption
     */
    pushWhitelistUsernames?: Array<string>;
    /**
     * 
     * @type {boolean}
     * @memberof EditBranchProtectionOption
     */
    requireSignedCommits?: boolean;
    /**
     * 
     * @type {number}
     * @memberof EditBranchProtectionOption
     */
    requiredApprovals?: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof EditBranchProtectionOption
     */
    statusCheckContexts?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof EditBranchProtectionOption
     */
    unprotectedFilePatterns?: string;
}
