/* tslint:disable */
/* eslint-disable */
/**
 * DCS (Gitea) API.
 * This documentation describes the DCS (Gitea) API.
 *
 * OpenAPI spec version: 1.16.7+dcs
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * EditMilestoneOption options for editing a milestone
 * @export
 * @interface EditMilestoneOption
 */
export interface EditMilestoneOption {
    /**
     * 
     * @type {string}
     * @memberof EditMilestoneOption
     */
    description?: string;
    /**
     * 
     * @type {Date}
     * @memberof EditMilestoneOption
     */
    dueOn?: Date;
    /**
     * 
     * @type {string}
     * @memberof EditMilestoneOption
     */
    state?: string;
    /**
     * 
     * @type {string}
     * @memberof EditMilestoneOption
     */
    title?: string;
}
