/* tslint:disable */
/* eslint-disable */
/**
 * DCS (Gitea) API.
 * This documentation describes the DCS (Gitea) API.
 *
 * OpenAPI spec version: 1.16.7+dcs
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CommitMeta } from './commit-meta';
import { CommitUser } from './commit-user';
/**
 * 
 * @export
 * @interface FileCommitResponse
 */
export interface FileCommitResponse {
    /**
     * 
     * @type {CommitUser}
     * @memberof FileCommitResponse
     */
    author?: CommitUser;
    /**
     * 
     * @type {CommitUser}
     * @memberof FileCommitResponse
     */
    committer?: CommitUser;
    /**
     * 
     * @type {Date}
     * @memberof FileCommitResponse
     */
    created?: Date;
    /**
     * 
     * @type {string}
     * @memberof FileCommitResponse
     */
    htmlUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof FileCommitResponse
     */
    message?: string;
    /**
     * 
     * @type {Array<CommitMeta>}
     * @memberof FileCommitResponse
     */
    parents?: Array<CommitMeta>;
    /**
     * 
     * @type {string}
     * @memberof FileCommitResponse
     */
    sha?: string;
    /**
     * 
     * @type {CommitMeta}
     * @memberof FileCommitResponse
     */
    tree?: CommitMeta;
    /**
     * 
     * @type {string}
     * @memberof FileCommitResponse
     */
    url?: string;
}
