/* tslint:disable */
/* eslint-disable */
/**
 * DCS (Gitea) API.
 * This documentation describes the DCS (Gitea) API.
 *
 * OpenAPI spec version: 1.16.7+dcs
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ContentsResponse } from './contents-response';
import { FileCommitResponse } from './file-commit-response';
import { PayloadCommitVerification } from './payload-commit-verification';
/**
 * FileResponse contains information about a repo's file
 * @export
 * @interface FileResponse
 */
export interface FileResponse {
    /**
     * 
     * @type {FileCommitResponse}
     * @memberof FileResponse
     */
    commit?: FileCommitResponse;
    /**
     * 
     * @type {ContentsResponse}
     * @memberof FileResponse
     */
    content?: ContentsResponse;
    /**
     * 
     * @type {PayloadCommitVerification}
     * @memberof FileResponse
     */
    verification?: PayloadCommitVerification;
}
