/* tslint:disable */
/* eslint-disable */
/**
 * DCS (Gitea) API.
 * This documentation describes the DCS (Gitea) API.
 *
 * OpenAPI spec version: 1.16.7+dcs
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * GeneralUISettings contains global ui settings exposed by API
 * @export
 * @interface GeneralUISettings
 */
export interface GeneralUISettings {
    /**
     * 
     * @type {Array<string>}
     * @memberof GeneralUISettings
     */
    allowedReactions?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof GeneralUISettings
     */
    customEmojis?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof GeneralUISettings
     */
    defaultTheme?: string;
}
