/* tslint:disable */
/* eslint-disable */
/**
 * DCS (Gitea) API.
 * This documentation describes the DCS (Gitea) API.
 *
 * OpenAPI spec version: 1.16.7+dcs
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * GeneralAPISettings contains global api settings exposed by it
 * @export
 * @interface GeneralAPISettings
 */
export interface GeneralAPISettings {
    /**
     * 
     * @type {number}
     * @memberof GeneralAPISettings
     */
    defaultGitTreesPerPage?: number;
    /**
     * 
     * @type {number}
     * @memberof GeneralAPISettings
     */
    defaultMaxBlobSize?: number;
    /**
     * 
     * @type {number}
     * @memberof GeneralAPISettings
     */
    defaultPagingNum?: number;
    /**
     * 
     * @type {number}
     * @memberof GeneralAPISettings
     */
    maxResponseItems?: number;
}
