/* tslint:disable */
/* eslint-disable */
/**
 * DCS (Gitea) API.
 * This documentation describes the DCS (Gitea) API.
 *
 * OpenAPI spec version: 1.16.7+dcs
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface GitObject
 */
export interface GitObject {
    /**
     * 
     * @type {string}
     * @memberof GitObject
     */
    sha?: string;
    /**
     * 
     * @type {string}
     * @memberof GitObject
     */
    type?: string;
    /**
     * 
     * @type {string}
     * @memberof GitObject
     */
    url?: string;
}
