/* tslint:disable */
/* eslint-disable */
/**
 * DCS (Gitea) API.
 * This documentation describes the DCS (Gitea) API.
 *
 * OpenAPI spec version: 1.16.7+dcs
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { GitEntry } from './git-entry';
/**
 * GitTreeResponse returns a git tree
 * @export
 * @interface GitTreeResponse
 */
export interface GitTreeResponse {
    /**
     * 
     * @type {number}
     * @memberof GitTreeResponse
     */
    page?: number;
    /**
     * 
     * @type {string}
     * @memberof GitTreeResponse
     */
    sha?: string;
    /**
     * 
     * @type {number}
     * @memberof GitTreeResponse
     */
    totalCount?: number;
    /**
     * 
     * @type {Array<GitEntry>}
     * @memberof GitTreeResponse
     */
    tree?: Array<GitEntry>;
    /**
     * 
     * @type {boolean}
     * @memberof GitTreeResponse
     */
    truncated?: boolean;
    /**
     * 
     * @type {string}
     * @memberof GitTreeResponse
     */
    url?: string;
}
