/* tslint:disable */
/* eslint-disable */
/**
 * DCS (Gitea) API.
 * This documentation describes the DCS (Gitea) API.
 *
 * OpenAPI spec version: 1.16.7+dcs
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * GPGKeyEmail an email attached to a GPGKey
 * @export
 * @interface GPGKeyEmail
 */
export interface GPGKeyEmail {
    /**
     * 
     * @type {string}
     * @memberof GPGKeyEmail
     */
    email?: string;
    /**
     * 
     * @type {boolean}
     * @memberof GPGKeyEmail
     */
    verified?: boolean;
}
