/* tslint:disable */
/* eslint-disable */
/**
 * DCS (Gitea) API.
 * This documentation describes the DCS (Gitea) API.
 *
 * OpenAPI spec version: 1.16.7+dcs
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * Hook a hook is a web hook when one repository changed
 * @export
 * @interface Hook
 */
export interface Hook {
    /**
     * 
     * @type {boolean}
     * @memberof Hook
     */
    active?: boolean;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof Hook
     */
    config?: { [key: string]: string; };
    /**
     * 
     * @type {Date}
     * @memberof Hook
     */
    createdAt?: Date;
    /**
     * 
     * @type {Array<string>}
     * @memberof Hook
     */
    events?: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof Hook
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof Hook
     */
    type?: string;
    /**
     * 
     * @type {Date}
     * @memberof Hook
     */
    updatedAt?: Date;
}
