/* tslint:disable */
/* eslint-disable */
/**
 * DCS (Gitea) API.
 * This documentation describes the DCS (Gitea) API.
 *
 * OpenAPI spec version: 1.16.7+dcs
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * InternalTracker represents settings for internal tracker
 * @export
 * @interface InternalTracker
 */
export interface InternalTracker {
    /**
     * Let only contributors track time (Built-in issue tracker)
     * @type {boolean}
     * @memberof InternalTracker
     */
    allowOnlyContributorsToTrackTime?: boolean;
    /**
     * Enable dependencies for issues and pull requests (Built-in issue tracker)
     * @type {boolean}
     * @memberof InternalTracker
     */
    enableIssueDependencies?: boolean;
    /**
     * Enable time tracking (Built-in issue tracker)
     * @type {boolean}
     * @memberof InternalTracker
     */
    enableTimeTracker?: boolean;
}
