/* tslint:disable */
/* eslint-disable */
/**
 * DCS (Gitea) API.
 * This documentation describes the DCS (Gitea) API.
 *
 * OpenAPI spec version: 1.16.7+dcs
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * IssueDeadline represents an issue deadline
 * @export
 * @interface IssueDeadline
 */
export interface IssueDeadline {
    /**
     * 
     * @type {Date}
     * @memberof IssueDeadline
     */
    dueDate?: Date;
}
