/* tslint:disable */
/* eslint-disable */
/**
 * DCS (Gitea) API.
 * This documentation describes the DCS (Gitea) API.
 *
 * OpenAPI spec version: 1.16.7+dcs
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * IssueTemplate represents an issue template for a repository
 * @export
 * @interface IssueTemplate
 */
export interface IssueTemplate {
    /**
     * 
     * @type {string}
     * @memberof IssueTemplate
     */
    about?: string;
    /**
     * 
     * @type {string}
     * @memberof IssueTemplate
     */
    content?: string;
    /**
     * 
     * @type {string}
     * @memberof IssueTemplate
     */
    fileName?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof IssueTemplate
     */
    labels?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof IssueTemplate
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof IssueTemplate
     */
    ref?: string;
    /**
     * 
     * @type {string}
     * @memberof IssueTemplate
     */
    title?: string;
}
