/* tslint:disable */
/* eslint-disable */
/**
 * DCS (Gitea) API.
 * This documentation describes the DCS (Gitea) API.
 *
 * OpenAPI spec version: 1.16.7+dcs
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * MarkdownOption markdown options
 * @export
 * @interface MarkdownOption
 */
export interface MarkdownOption {
    /**
     * Context to render  in: body
     * @type {string}
     * @memberof MarkdownOption
     */
    context?: string;
    /**
     * Mode to render  in: body
     * @type {string}
     * @memberof MarkdownOption
     */
    mode?: string;
    /**
     * Text markdown to render  in: body
     * @type {string}
     * @memberof MarkdownOption
     */
    text?: string;
    /**
     * Is it a wiki page ?  in: body
     * @type {boolean}
     * @memberof MarkdownOption
     */
    wiki?: boolean;
}
