/* tslint:disable */
/* eslint-disable */
/**
 * DCS (Gitea) API.
 * This documentation describes the DCS (Gitea) API.
 *
 * OpenAPI spec version: 1.16.7+dcs
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * MigrateRepoOptions options for migrating repository's this is used to interact with api v1
 * @export
 * @interface MigrateRepoOptions
 */
export interface MigrateRepoOptions {
    /**
     * 
     * @type {string}
     * @memberof MigrateRepoOptions
     */
    authPassword?: string;
    /**
     * 
     * @type {string}
     * @memberof MigrateRepoOptions
     */
    authToken?: string;
    /**
     * 
     * @type {string}
     * @memberof MigrateRepoOptions
     */
    authUsername?: string;
    /**
     * 
     * @type {string}
     * @memberof MigrateRepoOptions
     */
    cloneAddr: string;
    /**
     * 
     * @type {string}
     * @memberof MigrateRepoOptions
     */
    description?: string;
    /**
     * 
     * @type {boolean}
     * @memberof MigrateRepoOptions
     */
    issues?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof MigrateRepoOptions
     */
    labels?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof MigrateRepoOptions
     */
    lfs?: boolean;
    /**
     * 
     * @type {string}
     * @memberof MigrateRepoOptions
     */
    lfsEndpoint?: string;
    /**
     * 
     * @type {boolean}
     * @memberof MigrateRepoOptions
     */
    milestones?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof MigrateRepoOptions
     */
    mirror?: boolean;
    /**
     * 
     * @type {string}
     * @memberof MigrateRepoOptions
     */
    mirrorInterval?: string;
    /**
     * 
     * @type {boolean}
     * @memberof MigrateRepoOptions
     */
    _private?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof MigrateRepoOptions
     */
    pullRequests?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof MigrateRepoOptions
     */
    releases?: boolean;
    /**
     * 
     * @type {string}
     * @memberof MigrateRepoOptions
     */
    repoName: string;
    /**
     * Name of User or Organisation who will own Repo after migration
     * @type {string}
     * @memberof MigrateRepoOptions
     */
    repoOwner?: string;
    /**
     * 
     * @type {string}
     * @memberof MigrateRepoOptions
     */
    service?: MigrateRepoOptionsServiceEnum;
    /**
     * deprecated (only for backwards compatibility)
     * @type {number}
     * @memberof MigrateRepoOptions
     */
    uid?: number;
    /**
     * 
     * @type {boolean}
     * @memberof MigrateRepoOptions
     */
    wiki?: boolean;
}

/**
    * @export
    * @enum {string}
    */
export enum MigrateRepoOptionsServiceEnum {
    Git = 'git',
    Github = 'github',
    Gitea = 'gitea',
    Gitlab = 'gitlab'
}

