/* tslint:disable */
/* eslint-disable */
/**
 * DCS (Gitea) API.
 * This documentation describes the DCS (Gitea) API.
 *
 * OpenAPI spec version: 1.16.7+dcs
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * NodeInfoServices contains the third party sites this server can connect to via their application API
 * @export
 * @interface NodeInfoServices
 */
export interface NodeInfoServices {
    /**
     * 
     * @type {Array<string>}
     * @memberof NodeInfoServices
     */
    inbound?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof NodeInfoServices
     */
    outbound?: Array<string>;
}
