/* tslint:disable */
/* eslint-disable */
/**
 * DCS (Gitea) API.
 * This documentation describes the DCS (Gitea) API.
 *
 * OpenAPI spec version: 1.16.7+dcs
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * NodeInfoSoftware contains Metadata about server software in use
 * @export
 * @interface NodeInfoSoftware
 */
export interface NodeInfoSoftware {
    /**
     * 
     * @type {string}
     * @memberof NodeInfoSoftware
     */
    homepage?: string;
    /**
     * 
     * @type {string}
     * @memberof NodeInfoSoftware
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof NodeInfoSoftware
     */
    repository?: string;
    /**
     * 
     * @type {string}
     * @memberof NodeInfoSoftware
     */
    version?: string;
}
