/* tslint:disable */
/* eslint-disable */
/**
 * DCS (Gitea) API.
 * This documentation describes the DCS (Gitea) API.
 *
 * OpenAPI spec version: 1.16.7+dcs
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { NodeInfoUsageUsers } from './node-info-usage-users';
/**
 * NodeInfoUsage contains usage statistics for this server
 * @export
 * @interface NodeInfoUsage
 */
export interface NodeInfoUsage {
    /**
     * 
     * @type {number}
     * @memberof NodeInfoUsage
     */
    localComments?: number;
    /**
     * 
     * @type {number}
     * @memberof NodeInfoUsage
     */
    localPosts?: number;
    /**
     * 
     * @type {NodeInfoUsageUsers}
     * @memberof NodeInfoUsage
     */
    users?: NodeInfoUsageUsers;
}
