/* tslint:disable */
/* eslint-disable */
/**
 * DCS (Gitea) API.
 * This documentation describes the DCS (Gitea) API.
 *
 * OpenAPI spec version: 1.16.7+dcs
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Commit } from './commit';
/**
 * Note contains information related to a git note
 * @export
 * @interface Note
 */
export interface Note {
    /**
     * 
     * @type {Commit}
     * @memberof Note
     */
    commit?: Commit;
    /**
     * 
     * @type {string}
     * @memberof Note
     */
    message?: string;
}
