/* tslint:disable */
/* eslint-disable */
/**
 * DCS (Gitea) API.
 * This documentation describes the DCS (Gitea) API.
 *
 * OpenAPI spec version: 1.16.7+dcs
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { NotificationSubject } from './notification-subject';
import { Repository } from './repository';
/**
 * NotificationThread expose Notification on API
 * @export
 * @interface NotificationThread
 */
export interface NotificationThread {
    /**
     * 
     * @type {number}
     * @memberof NotificationThread
     */
    id?: number;
    /**
     * 
     * @type {boolean}
     * @memberof NotificationThread
     */
    pinned?: boolean;
    /**
     * 
     * @type {Repository}
     * @memberof NotificationThread
     */
    repository?: Repository;
    /**
     * 
     * @type {NotificationSubject}
     * @memberof NotificationThread
     */
    subject?: NotificationSubject;
    /**
     * 
     * @type {boolean}
     * @memberof NotificationThread
     */
    unread?: boolean;
    /**
     * 
     * @type {Date}
     * @memberof NotificationThread
     */
    updatedAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof NotificationThread
     */
    url?: string;
}
