/* tslint:disable */
/* eslint-disable */
/**
 * DCS (Gitea) API.
 * This documentation describes the DCS (Gitea) API.
 *
 * OpenAPI spec version: 1.16.7+dcs
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface OAuth2Application
 */
export interface OAuth2Application {
    /**
     * 
     * @type {string}
     * @memberof OAuth2Application
     */
    clientId?: string;
    /**
     * 
     * @type {string}
     * @memberof OAuth2Application
     */
    clientSecret?: string;
    /**
     * 
     * @type {Date}
     * @memberof OAuth2Application
     */
    created?: Date;
    /**
     * 
     * @type {number}
     * @memberof OAuth2Application
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof OAuth2Application
     */
    name?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof OAuth2Application
     */
    redirectUris?: Array<string>;
}
