/* tslint:disable */
/* eslint-disable */
/**
 * DCS (Gitea) API.
 * This documentation describes the DCS (Gitea) API.
 *
 * OpenAPI spec version: 1.16.7+dcs
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * OrganizationPermissions list different users permissions on an organization
 * @export
 * @interface OrganizationPermissions
 */
export interface OrganizationPermissions {
    /**
     * 
     * @type {boolean}
     * @memberof OrganizationPermissions
     */
    canCreateRepository?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof OrganizationPermissions
     */
    canRead?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof OrganizationPermissions
     */
    canWrite?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof OrganizationPermissions
     */
    isAdmin?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof OrganizationPermissions
     */
    isOwner?: boolean;
}
