/* tslint:disable */
/* eslint-disable */
/**
 * DCS (Gitea) API.
 * This documentation describes the DCS (Gitea) API.
 *
 * OpenAPI spec version: 1.16.7+dcs
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { PayloadCommitVerification } from './payload-commit-verification';
import { PayloadUser } from './payload-user';
/**
 * PayloadCommit represents a commit
 * @export
 * @interface PayloadCommit
 */
export interface PayloadCommit {
    /**
     * 
     * @type {Array<string>}
     * @memberof PayloadCommit
     */
    added?: Array<string>;
    /**
     * 
     * @type {PayloadUser}
     * @memberof PayloadCommit
     */
    author?: PayloadUser;
    /**
     * 
     * @type {PayloadUser}
     * @memberof PayloadCommit
     */
    committer?: PayloadUser;
    /**
     * sha1 hash of the commit
     * @type {string}
     * @memberof PayloadCommit
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof PayloadCommit
     */
    message?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof PayloadCommit
     */
    modified?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof PayloadCommit
     */
    removed?: Array<string>;
    /**
     * 
     * @type {Date}
     * @memberof PayloadCommit
     */
    timestamp?: Date;
    /**
     * 
     * @type {string}
     * @memberof PayloadCommit
     */
    url?: string;
    /**
     * 
     * @type {PayloadCommitVerification}
     * @memberof PayloadCommit
     */
    verification?: PayloadCommitVerification;
}
