/* tslint:disable */
/* eslint-disable */
/**
 * DCS (Gitea) API.
 * This documentation describes the DCS (Gitea) API.
 *
 * OpenAPI spec version: 1.16.7+dcs
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { PayloadUser } from './payload-user';
/**
 * PayloadCommitVerification represents the GPG verification of a commit
 * @export
 * @interface PayloadCommitVerification
 */
export interface PayloadCommitVerification {
    /**
     * 
     * @type {string}
     * @memberof PayloadCommitVerification
     */
    payload?: string;
    /**
     * 
     * @type {string}
     * @memberof PayloadCommitVerification
     */
    reason?: string;
    /**
     * 
     * @type {string}
     * @memberof PayloadCommitVerification
     */
    signature?: string;
    /**
     * 
     * @type {PayloadUser}
     * @memberof PayloadCommitVerification
     */
    signer?: PayloadUser;
    /**
     * 
     * @type {boolean}
     * @memberof PayloadCommitVerification
     */
    verified?: boolean;
}
