/* tslint:disable */
/* eslint-disable */
/**
 * DCS (Gitea) API.
 * This documentation describes the DCS (Gitea) API.
 *
 * OpenAPI spec version: 1.16.7+dcs
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { User } from './user';
/**
 * PublicKey publickey is a user key to push code to repository
 * @export
 * @interface PublicKey
 */
export interface PublicKey {
    /**
     * 
     * @type {Date}
     * @memberof PublicKey
     */
    createdAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof PublicKey
     */
    fingerprint?: string;
    /**
     * 
     * @type {number}
     * @memberof PublicKey
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof PublicKey
     */
    key?: string;
    /**
     * 
     * @type {string}
     * @memberof PublicKey
     */
    keyType?: string;
    /**
     * 
     * @type {boolean}
     * @memberof PublicKey
     */
    readOnly?: boolean;
    /**
     * 
     * @type {string}
     * @memberof PublicKey
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof PublicKey
     */
    url?: string;
    /**
     * 
     * @type {User}
     * @memberof PublicKey
     */
    user?: User;
}
