/* tslint:disable */
/* eslint-disable */
/**
 * DCS (Gitea) API.
 * This documentation describes the DCS (Gitea) API.
 *
 * OpenAPI spec version: 1.16.7+dcs
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Label } from './label';
import { Milestone } from './milestone';
import { PRBranchInfo } from './prbranch-info';
import { StateType } from './state-type';
import { User } from './user';
/**
 * PullRequest represents a pull request
 * @export
 * @interface PullRequest
 */
export interface PullRequest {
    /**
     * 
     * @type {User}
     * @memberof PullRequest
     */
    assignee?: User;
    /**
     * 
     * @type {Array<User>}
     * @memberof PullRequest
     */
    assignees?: Array<User>;
    /**
     * 
     * @type {PRBranchInfo}
     * @memberof PullRequest
     */
    base?: PRBranchInfo;
    /**
     * 
     * @type {string}
     * @memberof PullRequest
     */
    body?: string;
    /**
     * 
     * @type {Date}
     * @memberof PullRequest
     */
    closedAt?: Date;
    /**
     * 
     * @type {number}
     * @memberof PullRequest
     */
    comments?: number;
    /**
     * 
     * @type {Date}
     * @memberof PullRequest
     */
    createdAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof PullRequest
     */
    diffUrl?: string;
    /**
     * 
     * @type {Date}
     * @memberof PullRequest
     */
    dueDate?: Date;
    /**
     * 
     * @type {PRBranchInfo}
     * @memberof PullRequest
     */
    head?: PRBranchInfo;
    /**
     * 
     * @type {string}
     * @memberof PullRequest
     */
    htmlUrl?: string;
    /**
     * 
     * @type {number}
     * @memberof PullRequest
     */
    id?: number;
    /**
     * 
     * @type {boolean}
     * @memberof PullRequest
     */
    isLocked?: boolean;
    /**
     * 
     * @type {Array<Label>}
     * @memberof PullRequest
     */
    labels?: Array<Label>;
    /**
     * 
     * @type {string}
     * @memberof PullRequest
     */
    mergeBase?: string;
    /**
     * 
     * @type {string}
     * @memberof PullRequest
     */
    mergeCommitSha?: string;
    /**
     * 
     * @type {boolean}
     * @memberof PullRequest
     */
    mergeable?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PullRequest
     */
    merged?: boolean;
    /**
     * 
     * @type {Date}
     * @memberof PullRequest
     */
    mergedAt?: Date;
    /**
     * 
     * @type {User}
     * @memberof PullRequest
     */
    mergedBy?: User;
    /**
     * 
     * @type {Milestone}
     * @memberof PullRequest
     */
    milestone?: Milestone;
    /**
     * 
     * @type {number}
     * @memberof PullRequest
     */
    number?: number;
    /**
     * 
     * @type {string}
     * @memberof PullRequest
     */
    patchUrl?: string;
    /**
     * 
     * @type {StateType}
     * @memberof PullRequest
     */
    state?: StateType;
    /**
     * 
     * @type {string}
     * @memberof PullRequest
     */
    title?: string;
    /**
     * 
     * @type {Date}
     * @memberof PullRequest
     */
    updatedAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof PullRequest
     */
    url?: string;
    /**
     * 
     * @type {User}
     * @memberof PullRequest
     */
    user?: User;
}
