/* tslint:disable */
/* eslint-disable */
/**
 * DCS (Gitea) API.
 * This documentation describes the DCS (Gitea) API.
 *
 * OpenAPI spec version: 1.16.7+dcs
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { User } from './user';
/**
 * PullReviewComment represents a comment on a pull request review
 * @export
 * @interface PullReviewComment
 */
export interface PullReviewComment {
    /**
     * 
     * @type {string}
     * @memberof PullReviewComment
     */
    body?: string;
    /**
     * 
     * @type {string}
     * @memberof PullReviewComment
     */
    commitId?: string;
    /**
     * 
     * @type {Date}
     * @memberof PullReviewComment
     */
    createdAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof PullReviewComment
     */
    diffHunk?: string;
    /**
     * 
     * @type {string}
     * @memberof PullReviewComment
     */
    htmlUrl?: string;
    /**
     * 
     * @type {number}
     * @memberof PullReviewComment
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof PullReviewComment
     */
    originalCommitId?: string;
    /**
     * 
     * @type {number}
     * @memberof PullReviewComment
     */
    originalPosition?: number;
    /**
     * 
     * @type {string}
     * @memberof PullReviewComment
     */
    path?: string;
    /**
     * 
     * @type {number}
     * @memberof PullReviewComment
     */
    position?: number;
    /**
     * 
     * @type {number}
     * @memberof PullReviewComment
     */
    pullRequestReviewId?: number;
    /**
     * 
     * @type {string}
     * @memberof PullReviewComment
     */
    pullRequestUrl?: string;
    /**
     * 
     * @type {User}
     * @memberof PullReviewComment
     */
    resolver?: User;
    /**
     * 
     * @type {Date}
     * @memberof PullReviewComment
     */
    updatedAt?: Date;
    /**
     * 
     * @type {User}
     * @memberof PullReviewComment
     */
    user?: User;
}
