/* tslint:disable */
/* eslint-disable */
/**
 * DCS (Gitea) API.
 * This documentation describes the DCS (Gitea) API.
 *
 * OpenAPI spec version: 1.16.7+dcs
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ReviewStateType } from './review-state-type';
import { Team } from './team';
import { User } from './user';
/**
 * PullReview represents a pull request review
 * @export
 * @interface PullReview
 */
export interface PullReview {
    /**
     * 
     * @type {string}
     * @memberof PullReview
     */
    body?: string;
    /**
     * 
     * @type {number}
     * @memberof PullReview
     */
    commentsCount?: number;
    /**
     * 
     * @type {string}
     * @memberof PullReview
     */
    commitId?: string;
    /**
     * 
     * @type {boolean}
     * @memberof PullReview
     */
    dismissed?: boolean;
    /**
     * 
     * @type {string}
     * @memberof PullReview
     */
    htmlUrl?: string;
    /**
     * 
     * @type {number}
     * @memberof PullReview
     */
    id?: number;
    /**
     * 
     * @type {boolean}
     * @memberof PullReview
     */
    official?: boolean;
    /**
     * 
     * @type {string}
     * @memberof PullReview
     */
    pullRequestUrl?: string;
    /**
     * 
     * @type {boolean}
     * @memberof PullReview
     */
    stale?: boolean;
    /**
     * 
     * @type {ReviewStateType}
     * @memberof PullReview
     */
    state?: ReviewStateType;
    /**
     * 
     * @type {Date}
     * @memberof PullReview
     */
    submittedAt?: Date;
    /**
     * 
     * @type {Team}
     * @memberof PullReview
     */
    team?: Team;
    /**
     * 
     * @type {User}
     * @memberof PullReview
     */
    user?: User;
}
