/* tslint:disable */
/* eslint-disable */
/**
 * DCS (Gitea) API.
 * This documentation describes the DCS (Gitea) API.
 *
 * OpenAPI spec version: 1.16.7+dcs
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Organization } from './organization';
/**
 * Team represents a team in an organization
 * @export
 * @interface Team
 */
export interface Team {
    /**
     * 
     * @type {boolean}
     * @memberof Team
     */
    canCreateOrgRepo?: boolean;
    /**
     * 
     * @type {string}
     * @memberof Team
     */
    description?: string;
    /**
     * 
     * @type {number}
     * @memberof Team
     */
    id?: number;
    /**
     * 
     * @type {boolean}
     * @memberof Team
     */
    includesAllRepositories?: boolean;
    /**
     * 
     * @type {string}
     * @memberof Team
     */
    name?: string;
    /**
     * 
     * @type {Organization}
     * @memberof Team
     */
    organization?: Organization;
    /**
     * 
     * @type {string}
     * @memberof Team
     */
    permission?: TeamPermissionEnum;
    /**
     * 
     * @type {Array<string>}
     * @memberof Team
     */
    units?: Array<string>;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof Team
     */
    unitsMap?: { [key: string]: string; };
}

/**
    * @export
    * @enum {string}
    */
export enum TeamPermissionEnum {
    None = 'none',
    Read = 'read',
    Write = 'write',
    Admin = 'admin',
    Owner = 'owner'
}

