/* tslint:disable */
/* eslint-disable */
/**
 * DCS (Gitea) API.
 * This documentation describes the DCS (Gitea) API.
 *
 * OpenAPI spec version: 1.16.7+dcs
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * WatchInfo represents an API watch status of one repository
 * @export
 * @interface WatchInfo
 */
export interface WatchInfo {
    /**
     * 
     * @type {Date}
     * @memberof WatchInfo
     */
    createdAt?: Date;
    /**
     * 
     * @type {boolean}
     * @memberof WatchInfo
     */
    ignored?: boolean;
    /**
     * 
     * @type {any}
     * @memberof WatchInfo
     */
    reason?: any;
    /**
     * 
     * @type {string}
     * @memberof WatchInfo
     */
    repositoryUrl?: string;
    /**
     * 
     * @type {boolean}
     * @memberof WatchInfo
     */
    subscribed?: boolean;
    /**
     * 
     * @type {string}
     * @memberof WatchInfo
     */
    url?: string;
}
