/* tslint:disable */
/* eslint-disable */
/**
 * DCS (Gitea) API.
 * This documentation describes the DCS (Gitea) API.
 *
 * OpenAPI spec version: 1.16.7+dcs
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { WikiCommit } from './wiki-commit';
/**
 * WikiPage a wiki page
 * @export
 * @interface WikiPage
 */
export interface WikiPage {
    /**
     * 
     * @type {number}
     * @memberof WikiPage
     */
    commitCount?: number;
    /**
     * Page content, base64 encoded
     * @type {string}
     * @memberof WikiPage
     */
    contentBase64?: string;
    /**
     * 
     * @type {string}
     * @memberof WikiPage
     */
    footer?: string;
    /**
     * 
     * @type {string}
     * @memberof WikiPage
     */
    htmlUrl?: string;
    /**
     * 
     * @type {WikiCommit}
     * @memberof WikiPage
     */
    lastCommit?: WikiCommit;
    /**
     * 
     * @type {string}
     * @memberof WikiPage
     */
    sidebar?: string;
    /**
     * 
     * @type {string}
     * @memberof WikiPage
     */
    subUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof WikiPage
     */
    title?: string;
}
