/* tslint:disable */
/* eslint-disable */
/**
 * DCS (Gitea) API.
 * This documentation describes the DCS (Gitea) API.
 *
 * OpenAPI spec version: 1.16.7+dcs
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * APIError is an api error with a message
 * @export
 * @interface APIError
 */
export interface APIError {
    /**
     * 
     * @type {string}
     * @memberof APIError
     */
    message?: string;
    /**
     * 
     * @type {string}
     * @memberof APIError
     */
    url?: string;
}
