/* tslint:disable */
/* eslint-disable */
/**
 * DCS (Gitea) API.
 * This documentation describes the DCS (Gitea) API.
 *
 * OpenAPI spec version: 1.15.6a+dcs
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * Attachment a generic attachment
 * @export
 * @interface Attachment
 */
export interface Attachment {
    /**
     * 
     * @type {string}
     * @memberof Attachment
     */
    browserDownloadUrl?: any;
    /**
     * 
     * @type {Date}
     * @memberof Attachment
     */
    createdAt?: any;
    /**
     * 
     * @type {number}
     * @memberof Attachment
     */
    downloadCount?: any;
    /**
     * 
     * @type {number}
     * @memberof Attachment
     */
    id?: any;
    /**
     * 
     * @type {string}
     * @memberof Attachment
     */
    name?: any;
    /**
     * 
     * @type {number}
     * @memberof Attachment
     */
    size?: any;
    /**
     * 
     * @type {string}
     * @memberof Attachment
     */
    uuid?: any;
}
