/* tslint:disable */
/* eslint-disable */
/**
 * DCS (Gitea) API.
 * This documentation describes the DCS (Gitea) API.
 *
 * OpenAPI spec version: 1.15.6a+dcs
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * CatalogStage a repo's catalog stage metadata
 * @export
 * @interface CatalogStage
 */
export interface CatalogStage {
    /**
     * 
     * @type {string}
     * @memberof CatalogStage
     */
    branchOrTagName?: any;
    /**
     * 
     * @type {string}
     * @memberof CatalogStage
     */
    contentsUrl?: any;
    /**
     * 
     * @type {string}
     * @memberof CatalogStage
     */
    gitTreesUrl?: any;
    /**
     * 
     * @type {string}
     * @memberof CatalogStage
     */
    releaseUrl?: any;
    /**
     * 
     * @type {string}
     * @memberof CatalogStage
     */
    released?: any;
    /**
     * 
     * @type {string}
     * @memberof CatalogStage
     */
    tarballUrl?: any;
    /**
     * 
     * @type {string}
     * @memberof CatalogStage
     */
    zipballUrl?: any;
}
