/* tslint:disable */
/* eslint-disable */
/**
 * DCS (Gitea) API.
 * This documentation describes the DCS (Gitea) API.
 *
 * OpenAPI spec version: 1.16.7+dcs
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * CatalogStage a repo's catalog stage metadata
 * @export
 * @interface CatalogStage
 */
export interface CatalogStage {
    /**
     * 
     * @type {string}
     * @memberof CatalogStage
     */
    branchOrTagName?: string;
    /**
     * 
     * @type {string}
     * @memberof CatalogStage
     */
    contentsUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof CatalogStage
     */
    gitTreesUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof CatalogStage
     */
    releaseUrl?: string;
    /**
     * 
     * @type {Date}
     * @memberof CatalogStage
     */
    released?: Date;
    /**
     * 
     * @type {string}
     * @memberof CatalogStage
     */
    tarballUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof CatalogStage
     */
    zipballUrl?: string;
}
