/* tslint:disable */
/* eslint-disable */
/**
 * DCS (Gitea) API.
 * This documentation describes the DCS (Gitea) API.
 *
 * OpenAPI spec version: 1.15.6a+dcs
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * CombinedStatus holds the combined state of several statuses for a single commit
 * @export
 * @interface CombinedStatus
 */
export interface CombinedStatus {
    /**
     * 
     * @type {string}
     * @memberof CombinedStatus
     */
    commitUrl?: any;
    /**
     * 
     * @type {Repository}
     * @memberof CombinedStatus
     */
    repository?: any;
    /**
     * 
     * @type {string}
     * @memberof CombinedStatus
     */
    sha?: any;
    /**
     * 
     * @type {CommitStatusState}
     * @memberof CombinedStatus
     */
    state?: any;
    /**
     * 
     * @type {Array&lt;CommitStatus&gt;}
     * @memberof CombinedStatus
     */
    statuses?: any;
    /**
     * 
     * @type {number}
     * @memberof CombinedStatus
     */
    totalCount?: any;
    /**
     * 
     * @type {string}
     * @memberof CombinedStatus
     */
    url?: any;
}
