/* tslint:disable */
/* eslint-disable */
/**
 * DCS (Gitea) API.
 * This documentation describes the DCS (Gitea) API.
 *
 * OpenAPI spec version: 1.16.7+dcs
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CommitAffectedFiles } from './commit-affected-files';
import { CommitMeta } from './commit-meta';
import { RepoCommit } from './repo-commit';
import { User } from './user';
/**
 * 
 * @export
 * @interface Commit
 */
export interface Commit {
    /**
     * 
     * @type {User}
     * @memberof Commit
     */
    author?: User;
    /**
     * 
     * @type {RepoCommit}
     * @memberof Commit
     */
    commit?: RepoCommit;
    /**
     * 
     * @type {User}
     * @memberof Commit
     */
    committer?: User;
    /**
     * 
     * @type {Date}
     * @memberof Commit
     */
    created?: Date;
    /**
     * 
     * @type {Array<CommitAffectedFiles>}
     * @memberof Commit
     */
    files?: Array<CommitAffectedFiles>;
    /**
     * 
     * @type {string}
     * @memberof Commit
     */
    htmlUrl?: string;
    /**
     * 
     * @type {Array<CommitMeta>}
     * @memberof Commit
     */
    parents?: Array<CommitMeta>;
    /**
     * 
     * @type {string}
     * @memberof Commit
     */
    sha?: string;
    /**
     * 
     * @type {string}
     * @memberof Commit
     */
    url?: string;
}
