/* tslint:disable */
/* eslint-disable */
/**
 * DCS (Gitea) API.
 * This documentation describes the DCS (Gitea) API.
 *
 * OpenAPI spec version: 1.15.6a+dcs
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface Commit
 */
export interface Commit {
    /**
     * 
     * @type {User}
     * @memberof Commit
     */
    author?: any;
    /**
     * 
     * @type {RepoCommit}
     * @memberof Commit
     */
    commit?: any;
    /**
     * 
     * @type {User}
     * @memberof Commit
     */
    committer?: any;
    /**
     * 
     * @type {Date}
     * @memberof Commit
     */
    created?: any;
    /**
     * 
     * @type {Array&lt;CommitAffectedFiles&gt;}
     * @memberof Commit
     */
    files?: any;
    /**
     * 
     * @type {string}
     * @memberof Commit
     */
    htmlUrl?: any;
    /**
     * 
     * @type {Array&lt;CommitMeta&gt;}
     * @memberof Commit
     */
    parents?: any;
    /**
     * 
     * @type {string}
     * @memberof Commit
     */
    sha?: any;
    /**
     * 
     * @type {string}
     * @memberof Commit
     */
    url?: any;
}
