/* tslint:disable */
/* eslint-disable */
/**
 * DCS (Gitea) API.
 * This documentation describes the DCS (Gitea) API.
 *
 * OpenAPI spec version: 1.16.7+dcs
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface CommitUser
 */
export interface CommitUser {
    /**
     * 
     * @type {string}
     * @memberof CommitUser
     */
    date?: string;
    /**
     * 
     * @type {string}
     * @memberof CommitUser
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof CommitUser
     */
    name?: string;
}
