/* tslint:disable */
/* eslint-disable */
/**
 * DCS (Gitea) API.
 * This documentation describes the DCS (Gitea) API.
 *
 * OpenAPI spec version: 1.16.7+dcs
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface CommitMeta
 */
export interface CommitMeta {
    /**
     * 
     * @type {Date}
     * @memberof CommitMeta
     */
    created?: Date;
    /**
     * 
     * @type {string}
     * @memberof CommitMeta
     */
    sha?: string;
    /**
     * 
     * @type {string}
     * @memberof CommitMeta
     */
    url?: string;
}
