/* tslint:disable */
/* eslint-disable */
/**
 * DCS (Gitea) API.
 * This documentation describes the DCS (Gitea) API.
 *
 * OpenAPI spec version: 1.16.7+dcs
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * CreateWikiPageOptions form for creating wiki
 * @export
 * @interface CreateWikiPageOptions
 */
export interface CreateWikiPageOptions {
    /**
     * content must be base64 encoded
     * @type {string}
     * @memberof CreateWikiPageOptions
     */
    contentBase64?: string;
    /**
     * optional commit message summarizing the change
     * @type {string}
     * @memberof CreateWikiPageOptions
     */
    message?: string;
    /**
     * page title. leave empty to keep unchanged
     * @type {string}
     * @memberof CreateWikiPageOptions
     */
    title?: string;
}
