/* tslint:disable */
/* eslint-disable */
/**
 * DCS (Gitea) API.
 * This documentation describes the DCS (Gitea) API.
 *
 * OpenAPI spec version: 1.16.7+dcs
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * CreateEmailOption options when creating email addresses
 * @export
 * @interface CreateEmailOption
 */
export interface CreateEmailOption {
    /**
     * email addresses to add
     * @type {Array<string>}
     * @memberof CreateEmailOption
     */
    emails?: Array<string>;
}
