/* tslint:disable */
/* eslint-disable */
/**
 * DCS (Gitea) API.
 * This documentation describes the DCS (Gitea) API.
 *
 * OpenAPI spec version: 1.15.6a+dcs
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * CreateStatusOption holds the information needed to create a new CommitStatus for a Commit
 * @export
 * @interface CreateStatusOption
 */
export interface CreateStatusOption {
    /**
     * 
     * @type {string}
     * @memberof CreateStatusOption
     */
    context?: any;
    /**
     * 
     * @type {string}
     * @memberof CreateStatusOption
     */
    description?: any;
    /**
     * 
     * @type {CommitStatusState}
     * @memberof CreateStatusOption
     */
    state?: any;
    /**
     * 
     * @type {string}
     * @memberof CreateStatusOption
     */
    targetUrl?: any;
}
