/* tslint:disable */
/* eslint-disable */
/**
 * DCS (Gitea) API.
 * This documentation describes the DCS (Gitea) API.
 *
 * OpenAPI spec version: 1.16.7+dcs
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * CreateOAuth2ApplicationOptions holds options to create an oauth2 application
 * @export
 * @interface CreateOAuth2ApplicationOptions
 */
export interface CreateOAuth2ApplicationOptions {
    /**
     * 
     * @type {string}
     * @memberof CreateOAuth2ApplicationOptions
     */
    name?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof CreateOAuth2ApplicationOptions
     */
    redirectUris?: Array<string>;
}
