/* tslint:disable */
/* eslint-disable */
/**
 * DCS (Gitea) API.
 * This documentation describes the DCS (Gitea) API.
 *
 * OpenAPI spec version: 1.16.7+dcs
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * CreatePullRequestOption options when creating a pull request
 * @export
 * @interface CreatePullRequestOption
 */
export interface CreatePullRequestOption {
    /**
     * 
     * @type {string}
     * @memberof CreatePullRequestOption
     */
    assignee?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof CreatePullRequestOption
     */
    assignees?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof CreatePullRequestOption
     */
    base?: string;
    /**
     * 
     * @type {string}
     * @memberof CreatePullRequestOption
     */
    body?: string;
    /**
     * 
     * @type {Date}
     * @memberof CreatePullRequestOption
     */
    dueDate?: Date;
    /**
     * 
     * @type {string}
     * @memberof CreatePullRequestOption
     */
    head?: string;
    /**
     * 
     * @type {Array<number>}
     * @memberof CreatePullRequestOption
     */
    labels?: Array<number>;
    /**
     * 
     * @type {number}
     * @memberof CreatePullRequestOption
     */
    milestone?: number;
    /**
     * 
     * @type {string}
     * @memberof CreatePullRequestOption
     */
    title?: string;
}
