/* tslint:disable */
/* eslint-disable */
/**
 * DCS (Gitea) API.
 * This documentation describes the DCS (Gitea) API.
 *
 * OpenAPI spec version: 1.16.7+dcs
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CreateHookOptionConfig } from './create-hook-option-config';
/**
 * CreateHookOption options when create a hook
 * @export
 * @interface CreateHookOption
 */
export interface CreateHookOption {
    /**
     * 
     * @type {boolean}
     * @memberof CreateHookOption
     */
    active?: boolean;
    /**
     * 
     * @type {string}
     * @memberof CreateHookOption
     */
    branchFilter?: string;
    /**
     * 
     * @type {CreateHookOptionConfig}
     * @memberof CreateHookOption
     */
    config: CreateHookOptionConfig;
    /**
     * 
     * @type {Array<string>}
     * @memberof CreateHookOption
     */
    events?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof CreateHookOption
     */
    type: CreateHookOptionTypeEnum;
}

/**
    * @export
    * @enum {string}
    */
export enum CreateHookOptionTypeEnum {
    Dingtalk = 'dingtalk',
    Discord = 'discord',
    Gitea = 'gitea',
    Gogs = 'gogs',
    Msteams = 'msteams',
    Slack = 'slack',
    Telegram = 'telegram',
    Feishu = 'feishu',
    Wechatwork = 'wechatwork'
}

