/* tslint:disable */
/* eslint-disable */
/**
 * DCS (Gitea) API.
 * This documentation describes the DCS (Gitea) API.
 *
 * OpenAPI spec version: 1.16.7+dcs
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * CreateLabelOption options for creating a label
 * @export
 * @interface CreateLabelOption
 */
export interface CreateLabelOption {
    /**
     * 
     * @type {string}
     * @memberof CreateLabelOption
     */
    color: string;
    /**
     * 
     * @type {string}
     * @memberof CreateLabelOption
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateLabelOption
     */
    name: string;
}
