/* tslint:disable */
/* eslint-disable */
/**
 * DCS (Gitea) API.
 * This documentation describes the DCS (Gitea) API.
 *
 * OpenAPI spec version: 1.15.6a+dcs
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * CreatePullReviewOptions are options to create a pull review
 * @export
 * @interface CreatePullReviewOptions
 */
export interface CreatePullReviewOptions {
    /**
     * 
     * @type {string}
     * @memberof CreatePullReviewOptions
     */
    body?: any;
    /**
     * 
     * @type {Array&lt;CreatePullReviewComment&gt;}
     * @memberof CreatePullReviewOptions
     */
    comments?: any;
    /**
     * 
     * @type {string}
     * @memberof CreatePullReviewOptions
     */
    commitId?: any;
    /**
     * 
     * @type {ReviewStateType}
     * @memberof CreatePullReviewOptions
     */
    event?: any;
}
