/* tslint:disable */
/* eslint-disable */
/**
 * DCS (Gitea) API.
 * This documentation describes the DCS (Gitea) API.
 *
 * OpenAPI spec version: 1.15.6a+dcs
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * Cron represents a Cron task
 * @export
 * @interface Cron
 */
export interface Cron {
    /**
     * 
     * @type {number}
     * @memberof Cron
     */
    execTimes?: any;
    /**
     * 
     * @type {string}
     * @memberof Cron
     */
    name?: any;
    /**
     * 
     * @type {Date}
     * @memberof Cron
     */
    next?: any;
    /**
     * 
     * @type {Date}
     * @memberof Cron
     */
    prev?: any;
    /**
     * 
     * @type {string}
     * @memberof Cron
     */
    schedule?: any;
}
