/* tslint:disable */
/* eslint-disable */
/**
 * DCS (Gitea) API.
 * This documentation describes the DCS (Gitea) API.
 *
 * OpenAPI spec version: 1.15.6a+dcs
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * EditOrgOption options for editing an organization
 * @export
 * @interface EditOrgOption
 */
export interface EditOrgOption {
    /**
     * 
     * @type {string}
     * @memberof EditOrgOption
     */
    description?: any;
    /**
     * 
     * @type {string}
     * @memberof EditOrgOption
     */
    fullName?: any;
    /**
     * 
     * @type {string}
     * @memberof EditOrgOption
     */
    location?: any;
    /**
     * 
     * @type {boolean}
     * @memberof EditOrgOption
     */
    repoAdminChangeTeamAccess?: any;
    /**
     * possible values are `public`, `limited` or `private`
     * @type {string}
     * @memberof EditOrgOption
     */
    visibility?: EditOrgOptionVisibilityEnum;
    /**
     * 
     * @type {string}
     * @memberof EditOrgOption
     */
    website?: any;
}

/**
    * @export
    * @enum {string}
    */
export enum EditOrgOptionVisibilityEnum {
    Public = 'public',
    Limited = 'limited',
    Private = 'private'
}

