/* tslint:disable */
/* eslint-disable */
/**
 * DCS (Gitea) API.
 * This documentation describes the DCS (Gitea) API.
 *
 * OpenAPI spec version: 1.15.6a+dcs
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * FileLinksResponse contains the links for a repo's file
 * @export
 * @interface FileLinksResponse
 */
export interface FileLinksResponse {
    /**
     * 
     * @type {string}
     * @memberof FileLinksResponse
     */
    git?: any;
    /**
     * 
     * @type {string}
     * @memberof FileLinksResponse
     */
    html?: any;
    /**
     * 
     * @type {string}
     * @memberof FileLinksResponse
     */
    self?: any;
}
