/* tslint:disable */
/* eslint-disable */
/**
 * DCS (Gitea) API.
 * This documentation describes the DCS (Gitea) API.
 *
 * OpenAPI spec version: 1.15.6a+dcs
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface FileCommitResponse
 */
export interface FileCommitResponse {
    /**
     * 
     * @type {CommitUser}
     * @memberof FileCommitResponse
     */
    author?: any;
    /**
     * 
     * @type {CommitUser}
     * @memberof FileCommitResponse
     */
    committer?: any;
    /**
     * 
     * @type {Date}
     * @memberof FileCommitResponse
     */
    created?: any;
    /**
     * 
     * @type {string}
     * @memberof FileCommitResponse
     */
    htmlUrl?: any;
    /**
     * 
     * @type {string}
     * @memberof FileCommitResponse
     */
    message?: any;
    /**
     * 
     * @type {Array&lt;CommitMeta&gt;}
     * @memberof FileCommitResponse
     */
    parents?: any;
    /**
     * 
     * @type {string}
     * @memberof FileCommitResponse
     */
    sha?: any;
    /**
     * 
     * @type {CommitMeta}
     * @memberof FileCommitResponse
     */
    tree?: any;
    /**
     * 
     * @type {string}
     * @memberof FileCommitResponse
     */
    url?: any;
}
