/* tslint:disable */
/* eslint-disable */
/**
 * DCS (Gitea) API.
 * This documentation describes the DCS (Gitea) API.
 *
 * OpenAPI spec version: 1.15.6a+dcs
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * FileDeleteResponse contains information about a repo's file that was deleted
 * @export
 * @interface FileDeleteResponse
 */
export interface FileDeleteResponse {
    /**
     * 
     * @type {FileCommitResponse}
     * @memberof FileDeleteResponse
     */
    commit?: any;
    /**
     * 
     * @type {any}
     * @memberof FileDeleteResponse
     */
    content?: any;
    /**
     * 
     * @type {PayloadCommitVerification}
     * @memberof FileDeleteResponse
     */
    verification?: any;
}
