/* tslint:disable */
/* eslint-disable */
/**
 * DCS (Gitea) API.
 * This documentation describes the DCS (Gitea) API.
 *
 * OpenAPI spec version: 1.15.6a+dcs
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * GeneralRepoSettings contains global repository settings exposed by API
 * @export
 * @interface GeneralRepoSettings
 */
export interface GeneralRepoSettings {
    /**
     * 
     * @type {boolean}
     * @memberof GeneralRepoSettings
     */
    httpGitDisabled?: any;
    /**
     * 
     * @type {boolean}
     * @memberof GeneralRepoSettings
     */
    lfsDisabled?: any;
    /**
     * 
     * @type {boolean}
     * @memberof GeneralRepoSettings
     */
    migrationsDisabled?: any;
    /**
     * 
     * @type {boolean}
     * @memberof GeneralRepoSettings
     */
    mirrorsDisabled?: any;
    /**
     * 
     * @type {boolean}
     * @memberof GeneralRepoSettings
     */
    starsDisabled?: any;
    /**
     * 
     * @type {boolean}
     * @memberof GeneralRepoSettings
     */
    timeTrackingDisabled?: any;
}
