/* tslint:disable */
/* eslint-disable */
/**
 * DCS (Gitea) API.
 * This documentation describes the DCS (Gitea) API.
 *
 * OpenAPI spec version: 1.16.7+dcs
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * GeneralAttachmentSettings contains global Attachment settings exposed by API
 * @export
 * @interface GeneralAttachmentSettings
 */
export interface GeneralAttachmentSettings {
    /**
     * 
     * @type {string}
     * @memberof GeneralAttachmentSettings
     */
    allowedTypes?: string;
    /**
     * 
     * @type {boolean}
     * @memberof GeneralAttachmentSettings
     */
    enabled?: boolean;
    /**
     * 
     * @type {number}
     * @memberof GeneralAttachmentSettings
     */
    maxFiles?: number;
    /**
     * 
     * @type {number}
     * @memberof GeneralAttachmentSettings
     */
    maxSize?: number;
}
