/* tslint:disable */
/* eslint-disable */
/**
 * DCS (Gitea) API.
 * This documentation describes the DCS (Gitea) API.
 *
 * OpenAPI spec version: 1.15.6a+dcs
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * GitBlobResponse represents a git blob
 * @export
 * @interface GitBlobResponse
 */
export interface GitBlobResponse {
    /**
     * 
     * @type {string}
     * @memberof GitBlobResponse
     */
    content?: any;
    /**
     * 
     * @type {string}
     * @memberof GitBlobResponse
     */
    encoding?: any;
    /**
     * 
     * @type {string}
     * @memberof GitBlobResponse
     */
    sha?: any;
    /**
     * 
     * @type {number}
     * @memberof GitBlobResponse
     */
    size?: any;
    /**
     * 
     * @type {string}
     * @memberof GitBlobResponse
     */
    url?: any;
}
