/* tslint:disable */
/* eslint-disable */
/**
 * DCS (Gitea) API.
 * This documentation describes the DCS (Gitea) API.
 *
 * OpenAPI spec version: 1.16.7+dcs
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * GitHook represents a Git repository hook
 * @export
 * @interface GitHook
 */
export interface GitHook {
    /**
     * 
     * @type {string}
     * @memberof GitHook
     */
    content?: string;
    /**
     * 
     * @type {boolean}
     * @memberof GitHook
     */
    isActive?: boolean;
    /**
     * 
     * @type {string}
     * @memberof GitHook
     */
    name?: string;
}
