/* tslint:disable */
/* eslint-disable */
/**
 * DCS (Gitea) API.
 * This documentation describes the DCS (Gitea) API.
 *
 * OpenAPI spec version: 1.16.7+dcs
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { GPGKeyEmail } from './gpgkey-email';
/**
 * GPGKey a user GPG key to sign commit and tag in repository
 * @export
 * @interface GPGKey
 */
export interface GPGKey {
    /**
     * 
     * @type {boolean}
     * @memberof GPGKey
     */
    canCertify?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof GPGKey
     */
    canEncryptComms?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof GPGKey
     */
    canEncryptStorage?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof GPGKey
     */
    canSign?: boolean;
    /**
     * 
     * @type {Date}
     * @memberof GPGKey
     */
    createdAt?: Date;
    /**
     * 
     * @type {Array<GPGKeyEmail>}
     * @memberof GPGKey
     */
    emails?: Array<GPGKeyEmail>;
    /**
     * 
     * @type {Date}
     * @memberof GPGKey
     */
    expiresAt?: Date;
    /**
     * 
     * @type {number}
     * @memberof GPGKey
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof GPGKey
     */
    keyId?: string;
    /**
     * 
     * @type {string}
     * @memberof GPGKey
     */
    primaryKeyId?: string;
    /**
     * 
     * @type {string}
     * @memberof GPGKey
     */
    publicKey?: string;
    /**
     * 
     * @type {Array<GPGKey>}
     * @memberof GPGKey
     */
    subkeys?: Array<GPGKey>;
    /**
     * 
     * @type {boolean}
     * @memberof GPGKey
     */
    verified?: boolean;
}
