/* tslint:disable */
/* eslint-disable */
/**
 * DCS (Gitea) API.
 * This documentation describes the DCS (Gitea) API.
 *
 * OpenAPI spec version: 1.16.7+dcs
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Label } from './label';
import { Milestone } from './milestone';
import { PullRequestMeta } from './pull-request-meta';
import { RepositoryMeta } from './repository-meta';
import { StateType } from './state-type';
import { User } from './user';
/**
 * Issue represents an issue in a repository
 * @export
 * @interface Issue
 */
export interface Issue {
    /**
     * 
     * @type {User}
     * @memberof Issue
     */
    assignee?: User;
    /**
     * 
     * @type {Array<User>}
     * @memberof Issue
     */
    assignees?: Array<User>;
    /**
     * 
     * @type {string}
     * @memberof Issue
     */
    body?: string;
    /**
     * 
     * @type {Date}
     * @memberof Issue
     */
    closedAt?: Date;
    /**
     * 
     * @type {number}
     * @memberof Issue
     */
    comments?: number;
    /**
     * 
     * @type {Date}
     * @memberof Issue
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof Issue
     */
    dueDate?: Date;
    /**
     * 
     * @type {string}
     * @memberof Issue
     */
    htmlUrl?: string;
    /**
     * 
     * @type {number}
     * @memberof Issue
     */
    id?: number;
    /**
     * 
     * @type {boolean}
     * @memberof Issue
     */
    isLocked?: boolean;
    /**
     * 
     * @type {Array<Label>}
     * @memberof Issue
     */
    labels?: Array<Label>;
    /**
     * 
     * @type {Milestone}
     * @memberof Issue
     */
    milestone?: Milestone;
    /**
     * 
     * @type {number}
     * @memberof Issue
     */
    number?: number;
    /**
     * 
     * @type {string}
     * @memberof Issue
     */
    originalAuthor?: string;
    /**
     * 
     * @type {number}
     * @memberof Issue
     */
    originalAuthorId?: number;
    /**
     * 
     * @type {PullRequestMeta}
     * @memberof Issue
     */
    pullRequest?: PullRequestMeta;
    /**
     * 
     * @type {string}
     * @memberof Issue
     */
    ref?: string;
    /**
     * 
     * @type {RepositoryMeta}
     * @memberof Issue
     */
    repository?: RepositoryMeta;
    /**
     * 
     * @type {StateType}
     * @memberof Issue
     */
    state?: StateType;
    /**
     * 
     * @type {string}
     * @memberof Issue
     */
    title?: string;
    /**
     * 
     * @type {Date}
     * @memberof Issue
     */
    updatedAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof Issue
     */
    url?: string;
    /**
     * 
     * @type {User}
     * @memberof Issue
     */
    user?: User;
}
