/* tslint:disable */
/* eslint-disable */
/**
 * DCS (Gitea) API.
 * This documentation describes the DCS (Gitea) API.
 *
 * OpenAPI spec version: 1.16.7+dcs
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { GitServiceType } from './git-service-type';
/**
 * MigrateRepoForm form for migrating repository this is used to interact with web ui
 * @export
 * @interface MigrateRepoForm
 */
export interface MigrateRepoForm {
    /**
     * 
     * @type {string}
     * @memberof MigrateRepoForm
     */
    authPassword?: string;
    /**
     * 
     * @type {string}
     * @memberof MigrateRepoForm
     */
    authToken?: string;
    /**
     * 
     * @type {string}
     * @memberof MigrateRepoForm
     */
    authUsername?: string;
    /**
     * 
     * @type {string}
     * @memberof MigrateRepoForm
     */
    cloneAddr: string;
    /**
     * 
     * @type {string}
     * @memberof MigrateRepoForm
     */
    description?: string;
    /**
     * 
     * @type {boolean}
     * @memberof MigrateRepoForm
     */
    issues?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof MigrateRepoForm
     */
    labels?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof MigrateRepoForm
     */
    lfs?: boolean;
    /**
     * 
     * @type {string}
     * @memberof MigrateRepoForm
     */
    lfsEndpoint?: string;
    /**
     * 
     * @type {boolean}
     * @memberof MigrateRepoForm
     */
    milestones?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof MigrateRepoForm
     */
    mirror?: boolean;
    /**
     * 
     * @type {string}
     * @memberof MigrateRepoForm
     */
    mirrorInterval?: string;
    /**
     * 
     * @type {boolean}
     * @memberof MigrateRepoForm
     */
    _private?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof MigrateRepoForm
     */
    pullRequests?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof MigrateRepoForm
     */
    releases?: boolean;
    /**
     * 
     * @type {string}
     * @memberof MigrateRepoForm
     */
    repoName: string;
    /**
     * 
     * @type {GitServiceType}
     * @memberof MigrateRepoForm
     */
    service?: GitServiceType;
    /**
     * 
     * @type {number}
     * @memberof MigrateRepoForm
     */
    uid: number;
    /**
     * 
     * @type {boolean}
     * @memberof MigrateRepoForm
     */
    wiki?: boolean;
}
