/* tslint:disable */
/* eslint-disable */
/**
 * DCS (Gitea) API.
 * This documentation describes the DCS (Gitea) API.
 *
 * OpenAPI spec version: 1.16.7+dcs
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { NodeInfoServices } from './node-info-services';
import { NodeInfoSoftware } from './node-info-software';
import { NodeInfoUsage } from './node-info-usage';
/**
 * NodeInfo contains standardized way of exposing metadata about a server running one of the distributed social networks
 * @export
 * @interface NodeInfo
 */
export interface NodeInfo {
    /**
     * 
     * @type {any}
     * @memberof NodeInfo
     */
    metadata?: any;
    /**
     * 
     * @type {boolean}
     * @memberof NodeInfo
     */
    openRegistrations?: boolean;
    /**
     * 
     * @type {Array<string>}
     * @memberof NodeInfo
     */
    protocols?: Array<string>;
    /**
     * 
     * @type {NodeInfoServices}
     * @memberof NodeInfo
     */
    services?: NodeInfoServices;
    /**
     * 
     * @type {NodeInfoSoftware}
     * @memberof NodeInfo
     */
    software?: NodeInfoSoftware;
    /**
     * 
     * @type {NodeInfoUsage}
     * @memberof NodeInfo
     */
    usage?: NodeInfoUsage;
    /**
     * 
     * @type {string}
     * @memberof NodeInfo
     */
    version?: string;
}
