/* tslint:disable */
/* eslint-disable */
/**
 * DCS (Gitea) API.
 * This documentation describes the DCS (Gitea) API.
 *
 * OpenAPI spec version: 1.16.7+dcs
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * NodeInfoUsageUsers contains statistics about the users of this server
 * @export
 * @interface NodeInfoUsageUsers
 */
export interface NodeInfoUsageUsers {
    /**
     * 
     * @type {number}
     * @memberof NodeInfoUsageUsers
     */
    activeHalfyear?: number;
    /**
     * 
     * @type {number}
     * @memberof NodeInfoUsageUsers
     */
    activeMonth?: number;
    /**
     * 
     * @type {number}
     * @memberof NodeInfoUsageUsers
     */
    total?: number;
}
