/* tslint:disable */
/* eslint-disable */
/**
 * DCS (Gitea) API.
 * This documentation describes the DCS (Gitea) API.
 *
 * OpenAPI spec version: 1.16.7+dcs
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { NotifySubjectType } from './notify-subject-type';
import { StateType } from './state-type';
/**
 * NotificationSubject contains the notification subject (Issue/Pull/Commit)
 * @export
 * @interface NotificationSubject
 */
export interface NotificationSubject {
    /**
     * 
     * @type {string}
     * @memberof NotificationSubject
     */
    htmlUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof NotificationSubject
     */
    latestCommentHtmlUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof NotificationSubject
     */
    latestCommentUrl?: string;
    /**
     * 
     * @type {StateType}
     * @memberof NotificationSubject
     */
    state?: StateType;
    /**
     * 
     * @type {string}
     * @memberof NotificationSubject
     */
    title?: string;
    /**
     * 
     * @type {NotifySubjectType}
     * @memberof NotificationSubject
     */
    type?: NotifySubjectType;
    /**
     * 
     * @type {string}
     * @memberof NotificationSubject
     */
    url?: string;
}
