/* tslint:disable */
/* eslint-disable */
/**
 * DCS (Gitea) API.
 * This documentation describes the DCS (Gitea) API.
 *
 * OpenAPI spec version: 1.16.7+dcs
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * Organization represents an organization
 * @export
 * @interface Organization
 */
export interface Organization {
    /**
     * 
     * @type {string}
     * @memberof Organization
     */
    avatarUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof Organization
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof Organization
     */
    fullName?: string;
    /**
     * 
     * @type {number}
     * @memberof Organization
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof Organization
     */
    location?: string;
    /**
     * 
     * @type {boolean}
     * @memberof Organization
     */
    repoAdminChangeTeamAccess?: boolean;
    /**
     * DCS Customizations ***_/
     * @type {Array<string>}
     * @memberof Organization
     */
    repoLanguages?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof Organization
     */
    repoSubjects?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof Organization
     */
    username?: string;
    /**
     * 
     * @type {string}
     * @memberof Organization
     */
    visibility?: string;
    /**
     * 
     * @type {string}
     * @memberof Organization
     */
    website?: string;
}
