/* tslint:disable */
/* eslint-disable */
/**
 * DCS (Gitea) API.
 * This documentation describes the DCS (Gitea) API.
 *
 * OpenAPI spec version: 1.15.6a+dcs
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * PayloadUser represents the author or committer of a commit
 * @export
 * @interface PayloadUser
 */
export interface PayloadUser {
    /**
     * 
     * @type {string}
     * @memberof PayloadUser
     */
    email?: any;
    /**
     * Full name of the commit author
     * @type {string}
     * @memberof PayloadUser
     */
    name?: any;
    /**
     * 
     * @type {string}
     * @memberof PayloadUser
     */
    username?: any;
}
