/* tslint:disable */
/* eslint-disable */
/**
 * DCS (Gitea) API.
 * This documentation describes the DCS (Gitea) API.
 *
 * OpenAPI spec version: 1.15.6a+dcs
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * Permission represents a set of permissions
 * @export
 * @interface Permission
 */
export interface Permission {
    /**
     * 
     * @type {boolean}
     * @memberof Permission
     */
    admin?: any;
    /**
     * 
     * @type {boolean}
     * @memberof Permission
     */
    pull?: any;
    /**
     * 
     * @type {boolean}
     * @memberof Permission
     */
    push?: any;
}
