/* tslint:disable */
/* eslint-disable */
/**
 * DCS (Gitea) API.
 * This documentation describes the DCS (Gitea) API.
 *
 * OpenAPI spec version: 1.15.6a+dcs
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * PRBranchInfo information about a branch
 * @export
 * @interface PRBranchInfo
 */
export interface PRBranchInfo {
    /**
     * 
     * @type {string}
     * @memberof PRBranchInfo
     */
    label?: any;
    /**
     * 
     * @type {string}
     * @memberof PRBranchInfo
     */
    ref?: any;
    /**
     * 
     * @type {Repository}
     * @memberof PRBranchInfo
     */
    repo?: any;
    /**
     * 
     * @type {number}
     * @memberof PRBranchInfo
     */
    repoId?: any;
    /**
     * 
     * @type {string}
     * @memberof PRBranchInfo
     */
    sha?: any;
}
