/* tslint:disable */
/* eslint-disable */
/**
 * DCS (Gitea) API.
 * This documentation describes the DCS (Gitea) API.
 *
 * OpenAPI spec version: 1.16.7+dcs
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Repository } from './repository';
/**
 * PRBranchInfo information about a branch
 * @export
 * @interface PRBranchInfo
 */
export interface PRBranchInfo {
    /**
     * 
     * @type {string}
     * @memberof PRBranchInfo
     */
    label?: string;
    /**
     * 
     * @type {string}
     * @memberof PRBranchInfo
     */
    ref?: string;
    /**
     * 
     * @type {Repository}
     * @memberof PRBranchInfo
     */
    repo?: Repository;
    /**
     * 
     * @type {number}
     * @memberof PRBranchInfo
     */
    repoId?: number;
    /**
     * 
     * @type {string}
     * @memberof PRBranchInfo
     */
    sha?: string;
}
