/* tslint:disable */
/* eslint-disable */
/**
 * DCS (Gitea) API.
 * This documentation describes the DCS (Gitea) API.
 *
 * OpenAPI spec version: 1.15.6a+dcs
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * PublicKey publickey is a user key to push code to repository
 * @export
 * @interface PublicKey
 */
export interface PublicKey {
    /**
     * 
     * @type {Date}
     * @memberof PublicKey
     */
    createdAt?: any;
    /**
     * 
     * @type {string}
     * @memberof PublicKey
     */
    fingerprint?: any;
    /**
     * 
     * @type {number}
     * @memberof PublicKey
     */
    id?: any;
    /**
     * 
     * @type {string}
     * @memberof PublicKey
     */
    key?: any;
    /**
     * 
     * @type {string}
     * @memberof PublicKey
     */
    keyType?: any;
    /**
     * 
     * @type {boolean}
     * @memberof PublicKey
     */
    readOnly?: any;
    /**
     * 
     * @type {string}
     * @memberof PublicKey
     */
    title?: any;
    /**
     * 
     * @type {string}
     * @memberof PublicKey
     */
    url?: any;
    /**
     * 
     * @type {User}
     * @memberof PublicKey
     */
    user?: any;
}
