/* tslint:disable */
/* eslint-disable */
/**
 * DCS (Gitea) API.
 * This documentation describes the DCS (Gitea) API.
 *
 * OpenAPI spec version: 1.16.7+dcs
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Attachment } from './attachment';
import { User } from './user';
/**
 * Release represents a repository release
 * @export
 * @interface Release
 */
export interface Release {
    /**
     * 
     * @type {Array<Attachment>}
     * @memberof Release
     */
    assets?: Array<Attachment>;
    /**
     * 
     * @type {User}
     * @memberof Release
     */
    author?: User;
    /**
     * 
     * @type {string}
     * @memberof Release
     */
    body?: string;
    /**
     * 
     * @type {Date}
     * @memberof Release
     */
    createdAt?: Date;
    /**
     * 
     * @type {boolean}
     * @memberof Release
     */
    draft?: boolean;
    /**
     * 
     * @type {string}
     * @memberof Release
     */
    htmlUrl?: string;
    /**
     * 
     * @type {number}
     * @memberof Release
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof Release
     */
    name?: string;
    /**
     * 
     * @type {boolean}
     * @memberof Release
     */
    prerelease?: boolean;
    /**
     * 
     * @type {Date}
     * @memberof Release
     */
    publishedAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof Release
     */
    tagName?: string;
    /**
     * 
     * @type {string}
     * @memberof Release
     */
    tarballUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof Release
     */
    targetCommitish?: string;
    /**
     * 
     * @type {string}
     * @memberof Release
     */
    url?: string;
    /**
     * 
     * @type {string}
     * @memberof Release
     */
    zipballUrl?: string;
}
