/* tslint:disable */
/* eslint-disable */
/**
 * DCS (Gitea) API.
 * This documentation describes the DCS (Gitea) API.
 *
 * OpenAPI spec version: 1.16.7+dcs
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * RepositoryMeta basic repository information
 * @export
 * @interface RepositoryMeta
 */
export interface RepositoryMeta {
    /**
     * 
     * @type {string}
     * @memberof RepositoryMeta
     */
    fullName?: string;
    /**
     * 
     * @type {number}
     * @memberof RepositoryMeta
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof RepositoryMeta
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof RepositoryMeta
     */
    owner?: string;
}
