/* tslint:disable */
/* eslint-disable */
/**
 * DCS (Gitea) API.
 * This documentation describes the DCS (Gitea) API.
 *
 * OpenAPI spec version: 1.16.7+dcs
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CatalogStages } from './catalog-stages';
import { ExternalTracker } from './external-tracker';
import { ExternalWiki } from './external-wiki';
import { InternalTracker } from './internal-tracker';
import { Permission } from './permission';
import { RepoTransfer } from './repo-transfer';
import { User } from './user';
/**
 * Repository represents a repository
 * @export
 * @interface Repository
 */
export interface Repository {
    /**
     * 
     * @type {boolean}
     * @memberof Repository
     */
    allowMergeCommits?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Repository
     */
    allowRebase?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Repository
     */
    allowRebaseExplicit?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Repository
     */
    allowSquashMerge?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Repository
     */
    archived?: boolean;
    /**
     * 
     * @type {string}
     * @memberof Repository
     */
    avatarUrl?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof Repository
     */
    books?: Array<string>;
    /**
     * 
     * @type {CatalogStages}
     * @memberof Repository
     */
    catalog?: CatalogStages;
    /**
     * 
     * @type {string}
     * @memberof Repository
     */
    checkingLevel?: string;
    /**
     * 
     * @type {string}
     * @memberof Repository
     */
    cloneUrl?: string;
    /**
     * 
     * @type {Date}
     * @memberof Repository
     */
    createdAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof Repository
     */
    defaultBranch?: string;
    /**
     * 
     * @type {string}
     * @memberof Repository
     */
    defaultMergeStyle?: string;
    /**
     * 
     * @type {string}
     * @memberof Repository
     */
    description?: string;
    /**
     * 
     * @type {boolean}
     * @memberof Repository
     */
    empty?: boolean;
    /**
     * 
     * @type {ExternalTracker}
     * @memberof Repository
     */
    externalTracker?: ExternalTracker;
    /**
     * 
     * @type {ExternalWiki}
     * @memberof Repository
     */
    externalWiki?: ExternalWiki;
    /**
     * 
     * @type {boolean}
     * @memberof Repository
     */
    fork?: boolean;
    /**
     * 
     * @type {number}
     * @memberof Repository
     */
    forksCount?: number;
    /**
     * 
     * @type {string}
     * @memberof Repository
     */
    fullName?: string;
    /**
     * 
     * @type {boolean}
     * @memberof Repository
     */
    hasIssues?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Repository
     */
    hasProjects?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Repository
     */
    hasPullRequests?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Repository
     */
    hasWiki?: boolean;
    /**
     * 
     * @type {string}
     * @memberof Repository
     */
    htmlUrl?: string;
    /**
     * 
     * @type {number}
     * @memberof Repository
     */
    id?: number;
    /**
     * 
     * @type {boolean}
     * @memberof Repository
     */
    ignoreWhitespaceConflicts?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Repository
     */
    internal?: boolean;
    /**
     * 
     * @type {InternalTracker}
     * @memberof Repository
     */
    internalTracker?: InternalTracker;
    /**
     * 
     * @type {string}
     * @memberof Repository
     */
    language?: string;
    /**
     * 
     * @type {string}
     * @memberof Repository
     */
    languageDirection?: string;
    /**
     * 
     * @type {string}
     * @memberof Repository
     */
    languageTitle?: string;
    /**
     * 
     * @type {boolean}
     * @memberof Repository
     */
    mirror?: boolean;
    /**
     * 
     * @type {string}
     * @memberof Repository
     */
    mirrorInterval?: string;
    /**
     * 
     * @type {Date}
     * @memberof Repository
     */
    mirrorUpdated?: Date;
    /**
     * 
     * @type {string}
     * @memberof Repository
     */
    name?: string;
    /**
     * 
     * @type {number}
     * @memberof Repository
     */
    openIssuesCount?: number;
    /**
     * 
     * @type {number}
     * @memberof Repository
     */
    openPrCounter?: number;
    /**
     * 
     * @type {string}
     * @memberof Repository
     */
    originalUrl?: string;
    /**
     * 
     * @type {User}
     * @memberof Repository
     */
    owner?: User;
    /**
     * 
     * @type {Repository}
     * @memberof Repository
     */
    parent?: Repository;
    /**
     * 
     * @type {Permission}
     * @memberof Repository
     */
    permissions?: Permission;
    /**
     * 
     * @type {boolean}
     * @memberof Repository
     */
    _private?: boolean;
    /**
     * 
     * @type {number}
     * @memberof Repository
     */
    releaseCounter?: number;
    /**
     * 
     * @type {RepoTransfer}
     * @memberof Repository
     */
    repoTransfer?: RepoTransfer;
    /**
     * 
     * @type {number}
     * @memberof Repository
     */
    size?: number;
    /**
     * 
     * @type {string}
     * @memberof Repository
     */
    sshUrl?: string;
    /**
     * 
     * @type {number}
     * @memberof Repository
     */
    starsCount?: number;
    /**
     * 
     * @type {string}
     * @memberof Repository
     */
    subject?: string;
    /**
     * 
     * @type {boolean}
     * @memberof Repository
     */
    template?: boolean;
    /**
     * 
     * @type {string}
     * @memberof Repository
     */
    title?: string;
    /**
     * 
     * @type {Date}
     * @memberof Repository
     */
    updatedAt?: Date;
    /**
     * 
     * @type {number}
     * @memberof Repository
     */
    watchersCount?: number;
    /**
     * 
     * @type {string}
     * @memberof Repository
     */
    website?: string;
}
