/* tslint:disable */
/* eslint-disable */
/**
 * DCS (Gitea) API.
 * This documentation describes the DCS (Gitea) API.
 *
 * OpenAPI spec version: 1.16.7+dcs
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * StopWatch represent a running stopwatch
 * @export
 * @interface StopWatch
 */
export interface StopWatch {
    /**
     * 
     * @type {Date}
     * @memberof StopWatch
     */
    created?: Date;
    /**
     * 
     * @type {string}
     * @memberof StopWatch
     */
    duration?: string;
    /**
     * 
     * @type {number}
     * @memberof StopWatch
     */
    issueIndex?: number;
    /**
     * 
     * @type {string}
     * @memberof StopWatch
     */
    issueTitle?: string;
    /**
     * 
     * @type {string}
     * @memberof StopWatch
     */
    repoName?: string;
    /**
     * 
     * @type {string}
     * @memberof StopWatch
     */
    repoOwnerName?: string;
    /**
     * 
     * @type {number}
     * @memberof StopWatch
     */
    seconds?: number;
}
