/* tslint:disable */
/* eslint-disable */
/**
 * DCS (Gitea) API.
 * This documentation describes the DCS (Gitea) API.
 *
 * OpenAPI spec version: 1.16.7+dcs
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ReviewStateType } from './review-state-type';
/**
 * SubmitPullReviewOptions are options to submit a pending pull review
 * @export
 * @interface SubmitPullReviewOptions
 */
export interface SubmitPullReviewOptions {
    /**
     * 
     * @type {string}
     * @memberof SubmitPullReviewOptions
     */
    body?: string;
    /**
     * 
     * @type {ReviewStateType}
     * @memberof SubmitPullReviewOptions
     */
    event?: ReviewStateType;
}
