/* tslint:disable */
/* eslint-disable */
/**
 * DCS (Gitea) API.
 * This documentation describes the DCS (Gitea) API.
 *
 * OpenAPI spec version: 1.15.6a+dcs
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * TopicResponse for returning topics
 * @export
 * @interface TopicResponse
 */
export interface TopicResponse {
    /**
     * 
     * @type {Date}
     * @memberof TopicResponse
     */
    created?: any;
    /**
     * 
     * @type {number}
     * @memberof TopicResponse
     */
    id?: any;
    /**
     * 
     * @type {number}
     * @memberof TopicResponse
     */
    repoCount?: any;
    /**
     * 
     * @type {string}
     * @memberof TopicResponse
     */
    topicName?: any;
    /**
     * 
     * @type {Date}
     * @memberof TopicResponse
     */
    updated?: any;
}
