/* tslint:disable */
/* eslint-disable */
/**
 * DCS (Gitea) API.
 * This documentation describes the DCS (Gitea) API.
 *
 * OpenAPI spec version: 1.15.6a+dcs
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * User represents a user
 * @export
 * @interface User
 */
export interface User {
    /**
     * Is user active
     * @type {boolean}
     * @memberof User
     */
    active?: any;
    /**
     * URL to the user's avatar
     * @type {string}
     * @memberof User
     */
    avatarUrl?: any;
    /**
     * 
     * @type {Date}
     * @memberof User
     */
    created?: any;
    /**
     * the user's description
     * @type {string}
     * @memberof User
     */
    description?: any;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    email?: any;
    /**
     * user counts
     * @type {number}
     * @memberof User
     */
    followersCount?: any;
    /**
     * 
     * @type {number}
     * @memberof User
     */
    followingCount?: any;
    /**
     * the user's full name
     * @type {string}
     * @memberof User
     */
    fullName?: any;
    /**
     * the user's id
     * @type {number}
     * @memberof User
     */
    id?: any;
    /**
     * Is the user an administrator
     * @type {boolean}
     * @memberof User
     */
    isAdmin?: any;
    /**
     * User locale
     * @type {string}
     * @memberof User
     */
    language?: any;
    /**
     * 
     * @type {Date}
     * @memberof User
     */
    lastLogin?: any;
    /**
     * the user's location
     * @type {string}
     * @memberof User
     */
    location?: any;
    /**
     * the user's username
     * @type {string}
     * @memberof User
     */
    login?: any;
    /**
     * Is user login prohibited
     * @type {boolean}
     * @memberof User
     */
    prohibitLogin?: any;
    /**
     * DCS Customizations ***_/ Repo languages
     * @type {Array&lt;string&gt;}
     * @memberof User
     */
    repoLanguages?: any;
    /**
     * Repo subjects
     * @type {Array&lt;string&gt;}
     * @memberof User
     */
    repoSubjects?: any;
    /**
     * END DCS Customizations ***_/ Is user restricted
     * @type {boolean}
     * @memberof User
     */
    restricted?: any;
    /**
     * 
     * @type {number}
     * @memberof User
     */
    starredReposCount?: any;
    /**
     * User visibility level option: public, limited, private
     * @type {string}
     * @memberof User
     */
    visibility?: any;
    /**
     * the user's website
     * @type {string}
     * @memberof User
     */
    website?: any;
}
