/* tslint:disable */
/* eslint-disable */
/**
 * DCS (Gitea) API.
 * This documentation describes the DCS (Gitea) API.
 *
 * OpenAPI spec version: 1.15.6a+dcs
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * UserSettings represents user settings
 * @export
 * @interface UserSettings
 */
export interface UserSettings {
    /**
     * 
     * @type {string}
     * @memberof UserSettings
     */
    description?: any;
    /**
     * 
     * @type {string}
     * @memberof UserSettings
     */
    diffViewStyle?: any;
    /**
     * 
     * @type {string}
     * @memberof UserSettings
     */
    fullName?: any;
    /**
     * 
     * @type {boolean}
     * @memberof UserSettings
     */
    hideActivity?: any;
    /**
     * Privacy
     * @type {boolean}
     * @memberof UserSettings
     */
    hideEmail?: any;
    /**
     * 
     * @type {string}
     * @memberof UserSettings
     */
    language?: any;
    /**
     * 
     * @type {string}
     * @memberof UserSettings
     */
    location?: any;
    /**
     * 
     * @type {string}
     * @memberof UserSettings
     */
    theme?: any;
    /**
     * 
     * @type {string}
     * @memberof UserSettings
     */
    website?: any;
}
