/* tslint:disable */
/* eslint-disable */
/**
 * DCS (Gitea) API.
 * This documentation describes the DCS (Gitea) API.
 *
 * OpenAPI spec version: 1.16.7+dcs
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * UserSettings represents user settings
 * @export
 * @interface UserSettings
 */
export interface UserSettings {
    /**
     * 
     * @type {string}
     * @memberof UserSettings
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof UserSettings
     */
    diffViewStyle?: string;
    /**
     * 
     * @type {string}
     * @memberof UserSettings
     */
    fullName?: string;
    /**
     * 
     * @type {boolean}
     * @memberof UserSettings
     */
    hideActivity?: boolean;
    /**
     * Privacy
     * @type {boolean}
     * @memberof UserSettings
     */
    hideEmail?: boolean;
    /**
     * 
     * @type {string}
     * @memberof UserSettings
     */
    language?: string;
    /**
     * 
     * @type {string}
     * @memberof UserSettings
     */
    location?: string;
    /**
     * 
     * @type {string}
     * @memberof UserSettings
     */
    theme?: string;
    /**
     * 
     * @type {string}
     * @memberof UserSettings
     */
    website?: string;
}
