/* tslint:disable */
/* eslint-disable */
/**
 * DCS (Gitea) API.
 * This documentation describes the DCS (Gitea) API.
 *
 * OpenAPI spec version: 1.16.7+dcs
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { WikiCommit } from './wiki-commit';
/**
 * WikiPageMetaData wiki page meta information
 * @export
 * @interface WikiPageMetaData
 */
export interface WikiPageMetaData {
    /**
     * 
     * @type {string}
     * @memberof WikiPageMetaData
     */
    htmlUrl?: string;
    /**
     * 
     * @type {WikiCommit}
     * @memberof WikiPageMetaData
     */
    lastCommit?: WikiCommit;
    /**
     * 
     * @type {string}
     * @memberof WikiPageMetaData
     */
    subUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof WikiPageMetaData
     */
    title?: string;
}
